zowe-install/src/main/resources/scripts/api-mediation-start-gateway-template.sh
Signed-off-by: stevenhorsman <steven@uk.ibm.com>
fixes #105
=> Fix keystore path

zowe-install/src/main/resources/scripts/api-mediation-start-gateway-template.sh
This PR modifies options in the template to make it with sync with the configuration that is used for testing on Broadcom systems.
=> Improvements of api-mediation-start-gateway-template.sh

.codecov.yml, Jenkinsfile, README.md, codecov.sh
This PR is a POC of Codecov for coverage reporting. See https://codecov.io/gh/zowe/api-layer/branch/codecov
=> Publish coverage reports to Codecov.io to the pipeline

zowe-install/src/main/resources/scripts/api-mediation-start-catalog-template.sh
=> Turn on HTTPS for API catalog in Zowe

scripts/apiml_cm.sh
Signed-off-by: Petr Plavjanik <petr.plavjanik@broadcom.com>
=> Better message for insufficient privileges for z/OSMF keyring during installation 

gradle.properties
Signed-off-by: MarkAckert <Mark.Ackert@ca.com>
=> Set release version (0.3.0.)

gradle.properties
Signed-off-by: MarkAckert <Mark.Ackert@ca.com>
=> Set new snapshot version (0.3.1-SNAPSHOT)

gradle.properties, scripts/apiml_cm.sh, zowe-install/src/main/resources/scripts/setup-apiml-certificates-template.sh
This PR provides better messages for importing z/OSMF certificates.
Resolves https://github.com/zowe/zowe-install-packaging/issues/202
=> Better messages for z/OSMF trust and external certificates

docs/release.md
This documents the release automation done using https://github.com/researchgate/gradle-release
=> Release documentation

api-catalog-services/src/main/resources/application.yml, config/local/api-defs/zosmf-sample.yml, zowe-install/src/main/resources/scripts/api-mediation-start-catalog-template.sh, zowe-install/src/main/resources/scripts/api-mediation-start-gateway-template.sh
Signed-off-by: Petr Plavjanik <petr.plavjanik@broadcom.com>
=> Configure z/OSMF security for Zowe

apiml-auth/README.md, apiml-auth/lib/apimlAuth.js, apiml-auth/lib/apimlAuth.test.js, apiml-auth/lib/tokenInjector.js, apiml-auth/package.json, apiml-auth/pluginDefinition.json
Provides fixes for problems discovered during testing on z/OS.
- `axios` is not a dependency of zLUX so it has been replaced by standard `https` library
- better error handling
=> Fixes for APIML authentication plugin Zowe on z/OS

api-catalog-services/src/main/resources/application.yml, api-catalog-services/src/test/resources/application.yml, api-catalog-ui/frontend/package-lock.json
Signed-off-by: Vojta Oupicky <vojtech.oupicky@broadcom.com>
=> Update API catalog HP link

api-catalog-ui/frontend/src/components/Footer/Footer.jsx
Update the copyright in footer according to the latest information.
=> Update copyright in footer

api-catalog-ui/frontend/src/components/DetailPage/DetailPage.css
**Bug:** A div in the swagger-ui container on hte detail page was spilling ouside of the app.
**Fix:** Div width fixed.
=> Prevent div from spilling

README.md
This PR adds SonarQube badge with a link to https://jayne.zowe.org:9000/dashboard?id=zowe%3Aapi-mediation-layer where are SonarQube results. Please have a look to them as well and let me know what you think about this story: https://rally1.rallydev.com/#/72725828452ud/detail/userstory/286623856556
=> Add SonarQube badge

api-catalog-ui/frontend/src/components/Login/Login.jsx, api-catalog-ui/frontend/src/components/Login/Login.test.jsx
Login button is disabled only when login request is in progress.
If a user tries to log in with empty credentials show an error message.
=> Do not disable login button

CONTRIBUTING.md, integration-enabler-spring-v1/README.md, integration-enabler-spring-v2/README.md
Issue: https://github.com/zowe/api-layer/issues/226
Signed-off-by: Zikos, Christos <Christos.Zikos@ca.com>
=> Change gizafoundation to zowe on docs

api-catalog-ui/frontend/src/components/App/App.jsx
Related to this defect [https://rally1.rallydev.com/#/72725828452d/detail/defect/283874854844](https://rally1.rallydev.com/#/72725828452d/detail/defect/283874854844)
Signed-off-by: Andrea Tabone <andrea.tabone@ca.com>
=> Change route to /dashboard

docs/architecture/decisions/0003-discovery-of-externally-accessible-url-of-api-gateway.md
This documents the existing decision that was taken last year.
Signed-off-by: Petr Plavjanik <petr.plavjanik@broadcom.com>
=> ADR - Discovery of externally accessible URL of API Gateway

api-catalog-services/src/main/java/com/ca/mfaas/apicatalog/services/cached/CachedProductFamilyService.java, api-catalog-services/src/test/java/com/ca/mfaas/apicatalog/services/cached/CachedProductFamilyTest.java
https://rally1.rallydev.com/#/72725828452d/detail/defect/295080308288
Happy reviews!
=> API Catalog - Tile change not visible

scripts/publish_and_release.sh
Signed-off-by: Vsevolod Khanin <vsevolod.khanin@broadcom.com>
=> Path to bootstrap_gradle.sh fixed for publishing.

scripts/apiml_cm.sh
Signed-off-by: Zikos, Christos <Christos.Zikos@ca.com>
=> change export shell command

scripts/post_actions.py
Bug: Pull requests builds were assigned label "under CA testing" without triggering the Broadcom pipeline
Fix: Rework label check
Signed-off-by: Zikos, Christos <Christos.Zikos@ca.com>
=> Fix Pull Requests label bug

api-catalog-services/src/main/java/com/ca/mfaas/apicatalog/security/ComponentsConfiguration.java, api-catalog-services/src/main/resources/application.yml, api-catalog-ui/frontend/src/e2e/e2e.test.jsx, integration-tests/src/test/java/com/ca/mfaas/gatewayservice/LoginIntegrationTest.java, security-module/src/main/java/com/ca/mfaas/security/config/SecurityConfigurationProperties.java, security-service-client-spring/src/main/java/com/ca/apiml/security/config/SecurityConfigurationProperties.java
Setting cookie from persistent to session, so it gets cleared between sessions.
https://github.com/zowe/api-layer/issues/290
Happy review!
=> fix for issue #290

Jenkinsfile
Switch Jenkins to use new OpenJDK enabled docker image
=> Switch build to openJDK

docs/conformance.md
Signed-off-by: JirkaAichler <jiri.aichler@broadcom.com>
=> Fix typos in Conformance

gateway-service/src/main/resources/application.yml
Signed-off-by: janda06 <david.janda@broadcom.com>
=> fix for transform service in Zowe installation

docs/conformance.md
=> Update the conformance criteria document

Jenkinsfile, build.gradle, gradle.properties
increased phase timeouts
removed the increase of socket timeouts
Signed-off-by: janda06 <david.janda@broadcom.com>
=> Jenkins build optimization

docs/manual_tests.md
Small changes to manual_tests.md file.
Signed-off-by: Vsevolod Khanin <vsevolod.khanin@broadcom.com>
=> Manual test doc updated

Jenkinsfile, zowe-install/build.gradle
Modify jenkins Pipeline to publish the zowe-install.zip for every pull request and not only for master
=> Add step to publish Pull Request artifacts

api-catalog-services/src/main/resources/application.yml, apiml-common/src/main/java/com/ca/mfaas/product/logging/ApimlDependencyLogHider.java, apiml-common/src/test/java/com/ca/mfaas/product/logging/ApimlDependencyLogHiderTest.java, gateway-service/src/main/resources/application.yml
org.apache -> WARN
org.eclipse.jetty -> WARN
springfox -> WARN
=> Clean up Api Catalog - dependencies

api-catalog-ui/frontend/mocked-backend/assets/services/user-name-invalid.json, api-catalog-ui/frontend/mocked-backend/routes/routes.js, api-catalog-ui/frontend/mocked-backend/server.js, api-catalog-ui/frontend/src/components/Login/Login.jsx, api-catalog-ui/frontend/src/components/Login/Login.test.jsx, api-catalog-ui/frontend/src/components/Swagger/Swagger.jsx, api-catalog-ui/frontend/src/error-messages.json, api-catalog-ui/frontend/src/reducers/authentication.reducer.jsx
- Rewiew of messages for the UI.
-  Fix https://github.com/zowe/api-layer/issues/408
- Add additional informations to message in case swagger is not available (related to https://github.com/zowe/api-layer/issues/406)
- Add error handling for session expired message 
- Add unit tests
- Align messages with backend
=> Clean Up Api Catalog - UI

integration-tests/src/test/java/com/ca/mfaas/gatewayservice/ZosmfSsoIntegrationTest.java
Signed-off-by: Vsevolod Khanin <vsevolod.khanin@broadcom.com>
=> zosmf status code changed to SC_UNAUTHORIZED

zowe-install/src/main/resources/component-scripts/start.sh
Missed loglevel variable added to components start script.
Signed-off-by: Vsevolod Khanin <vsevolod.khanin@broadcom.com>
=> Missed loglevel variable added

Jenkinsfile, README.md, gradle.properties, gradle/sonar.gradle
As part of https://github.com/zowe/zowe-install-packaging/issues/832.
We will shutdown SonarQube on jayne.zowe.org soon.
=> Switch to SonarCloud

integration-tests/src/test/java/com/ca/mfaas/apicatalog/ApiCatalogSecurityIntegrationTest.java, integration-tests/src/test/java/com/ca/mfaas/gatewayservice/GatewaySecurityTest.java
Fixed problem with invalidation password to z/os after launching integration tests several times in row
Signed-off-by: Elena Kubantseva <elena.kubantseva@broadcom.com>
=> Fixed integration tests

zowe-install/src/main/resources/component-scripts/start.sh
Signed-off-by: Steven Horsman <steven@uk.ibm.com>
=> Add support for external_static_def

docs/idea-setup.md
=> Improve guide to IDEA based on the encountered issues

Jenkinsfile, build.gradle, gradle/generate-pom.gradle, gradle/versions.gradle
Signed-off-by: JirkaAichler <jiri.aichler@broadcom.com>
=> Add pom file to improve Code Insight scan results

gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/ZosmfFilter.java
Signed-off-by: JirkaAichler <jiri.aichler@broadcom.com>
=> Fix z/OSMF authorization header

common-service-core/src/main/java/org/zowe/apiml/util/MapUtils.java, common-service-core/src/test/java/org/zowe/apiml/util/MapUtilsTest.java, config/local/discoverable-client.yml, discoverable-client/src/main/resources/application.yml, discovery-service/src/main/java/org/zowe/apiml/discovery/staticdef/Service.java, discovery-service/src/main/java/org/zowe/apiml/discovery/staticdef/ServiceDefinitionProcessor.java, discovery-service/src/test/java/org/zowe/apiml/discovery/staticdef/ServiceDefinitionProcessorTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/EncodedCharactersTest.java, onboarding-enabler-java/build.gradle, onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/config/ApiMediationServiceConfig.java, onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/impl/ApiMediationClientImpl.java, onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigCreator.java, onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/util/ApiMediationServiceConfigReaderTest.java, onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigCreatorTest.java, onboarding-enabler-java/src/test/resources/additional-service-configuration.yml, onboarding-enabler-java/src/test/resources/service-configuration.yml, onboarding-enabler-spring/src/main/java/org/zowe/apiml/enable/register/RegisterToApiLayer.java, onboarding-enabler-spring/src/test/resources/application.yml
Add support for custom metadata addition through our onboarding enablers
=> enabler custom metadata support

discoverable-client/build.gradle
Signed-off-by: Ilkin Abdullayev <ilkin.abdullayev@broadcom.com>
=> Added missed libraries for discoverable client's ui

gateway-service/src/main/java/org/zowe/apiml/gateway/config/CacheConfig.java, gateway-service/src/main/resources/ehcache.xml, zowe-install/src/main/resources/component-scripts/start.sh
resolves #514
This PR allows to programatically set location of ehCache's storage files. It is also use in instal process of Zowe
=> change location of ehCache's storage files

Jenkinsfile, gradle/publish.gradle
Signed-off-by: Ilkin Abdullayev <ilkin.abdullayev@broadcom.com>
=> Changed scripts for publishing

build.gradle
Signed-off-by: Ilkin Abdullayev <ilkin.abdullayev@broadcom.com>
=> Hotfix junit platform

common-service-core/src/main/java/org/zowe/apiml/security/HttpsFactory.java
Flag verifySslCertificatesOfServices create different SSL content. This PR is changing them to user the same keystore settings.
=> fix keystore in rest template and http client by configuration

gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketActuatorEndpoint.java, gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketRoutedSession.java, gateway-service/src/test/java/org/zowe/apiml/gateway/ws/WebSocketActuatorEndpointTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/ws/WebSocketProxyServerHandlerTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/ws/WebSocketRoutedSessionTest.java
Clean and increase WebSocket related Coverage as per US627345
=> Increase WebSocket related code coverage

integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReader.java
=> Override all the properties with the system properties

gradle.properties
=> Change default settings to the ones with better performance

Jenkinsfile
=> Low impact cleanup of the Build

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
Removed implicit assign
added new label
added question template
=> Enhance issue templates

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
=> Update Issue Templates with the new Issue Management guidelines

zowe-install/src/main/resources/component-scripts/start.sh
This is required for PassTickets to be correctly generated.
Signed-off-by: Petr Plavjanik <plavjanik@gmail.com>
=> Add IRRRacf.jar to classpath of the API gateway

discovery-service/src/main/java/org/zowe/apiml/discovery/staticdef/ServiceDefinitionProcessor.java, discovery-service/src/main/java/org/zowe/apiml/discovery/staticdef/StaticRegistrationResult.java, discovery-service/src/main/resources/discovery-log-messages.yml, discovery-service/src/test/java/org/zowe/apiml/discovery/staticdef/ServiceDefinitionProcessorTest.java
=> Log the errors found in the static definitions

common-service-core/src/main/java/org/zowe/apiml/exception/MetadataValidationException.java, onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/impl/ApiMediationClientImpl.java
=> Prevent null pointer in case of missing SSL configuration

integration-tests/README.md, integration-tests/build.gradle, integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogEndpointIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/discoverableclient/DownloadApiIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/discoverableclient/GreetingApiIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/discoverableclient/MultipartPutIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/discoverableclient/UiIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/discoveryservice/EurekaInstancesIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/discoveryservice/staticdef/StaticClientRoutingEndpointsTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/EncodedCharactersTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/PageRedirectionTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/PassTicketTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/ZosmfSsoIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/util/categories/AdditionalLocalTest.java, integration-tests/src/test/java/org/zowe/apiml/util/categories/MainframeDependentTests.java, integration-tests/src/test/java/org/zowe/apiml/util/categories/SlowTests.java, integration-tests/src/test/java/org/zowe/apiml/util/categories/StartupCheck.java, integration-tests/src/test/java/org/zowe/apiml/util/categories/TestsNotMeantForZowe.java, integration-tests/src/test/java/org/zowe/apiml/util/categories/WebsocketTest.java, integration-tests/src/test/java/org/zowe/apiml/ws/WebSocketProxyTest.java
=> Add Category to exclude tests for Zowe testing

discoverable-client/build.gradle
=> Discoverable Client Thin jar fix

onboarding-enabler-java-sample-app/build.gradle
=> Update gradle tomcat plugin

Jenkinsfile, scripts/publish_and_release.sh
Build enabler v1
Remote cache used in publish process
=> Improve CICD on external Jenkins

Jenkinsfile, build.gradle, integration-tests/build.gradle, integration-tests/src/test/java/org/zowe/apiml/discoveryservice/EurekaInstancesIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/util/categories/Flaky.java
=> Run the integration tests on the external CI Jenkins server

integration-tests/build.gradle, integration-tests/src/test/java/org/zowe/apiml/discoverableclient/RequestInfoIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/discoveryservice/EurekaInstancesIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/GatewaySecurityTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/GatewayTimeoutTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/LogoutTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/PublicKeyIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/VersionEndpointTest.java, integration-tests/src/test/java/org/zowe/apiml/penetration/JwtPenTest.java, integration-tests/src/test/java/org/zowe/apiml/ws/WebSocketProxyTest.java
These tests have specific requirements.
=> Tag those tests that will fail for Zowe RC

Jenkinsfile
=> Store the logs from integration tests on the Jenkins to be able to explore them

onboarding-enabler-java/src/main/resources/config.properties
#577 add dummy file to avoid url configuration warn log
=> add dummy file to avoid warn log

README.md
=> replace codecov for sonar coverage badge

Jenkinsfile, api-catalog-ui/build.gradle, build.gradle, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/AuthenticationOnDeploymentTest.java
Mark Flaky test
Remove Useless task
Distinguish between dependency installation and build
=> Improve the CI CD Pipeline structure

integration-tests/src/test/java/org/zowe/apiml/zaasclient/ZaasClientIntegrationTest.java, zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/CloseableClientProviderTest.java
=> Move setup code outside of assertThrows

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/security/SecurityConfiguration.java, api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIRefreshController.java, api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIRefreshControllerExceptionHandler.java, api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIResponse.java, api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIService.java, api-catalog-services/src/main/resources/apicatalog-log-messages.yml, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIRefreshControllerTest.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIServiceTest.java, discovery-service/src/main/resources/application.yml, integration-tests/README.md, integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogEndpointIntegrationTest.java
=> Api catalog backend refresh endpoint

api-catalog-ui/frontend/src/components/Dashboard/Dashboard.jsx, api-catalog-ui/frontend/src/components/Error/ErrorDialog.jsx, api-catalog-ui/frontend/src/components/Error/ErrorDialog.test.jsx
Create separate component for the Dialog and add unit test
=> UI refactoring

CHANGELOG.md
=> Add the key changes for the 1.12 release

onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidator.java
=> Remove ciphers from validation as they are optional

CONTRIBUTING.md, README.md
=> US644826 - add Slack contacts

discoverable-client/src/main/resources/application.yml, gateway-service/src/main/java/org/zowe/apiml/gateway/config/EurekaEventsRegistry.java, gateway-service/src/main/java/org/zowe/apiml/gateway/metadata/service/EurekaApplications.java, gateway-service/src/main/java/org/zowe/apiml/gateway/metadata/service/MetadataProcessor.java, gateway-service/src/test/java/org/zowe/apiml/gateway/config/EurekaEventsRegistryTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/metadata/service/EurekaApplicationsTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/metadata/service/MetadataProcessorTest.java
=> Timeout per service implementation

gateway-service/src/test/java/org/zowe/apiml/acceptance/TimeoutPerServiceTest.java
Testing the solution for #683 
=> Verify the configuration override of the timeouts

gateway-service/src/test/java/org/zowe/apiml/acceptance/TimeoutPerServiceTest.java, gateway-service/src/test/java/org/zowe/apiml/acceptance/common/AcceptanceTest.java, gateway-service/src/test/java/org/zowe/apiml/acceptance/common/AcceptanceTestWithBasePath.java, gateway-service/src/test/java/org/zowe/apiml/acceptance/common/AcceptanceTestWithTwoServices.java, gateway-service/src/test/java/org/zowe/apiml/acceptance/common/Service.java, gateway-service/src/test/java/org/zowe/apiml/acceptance/netflix/ApplicationRegistry.java
Adapt the Acceptance test infrastructure to remove duplication for further tests
Part of the solution for #384 
=> Clean acceptance tests

docs/idea-setup.md
Signed-off-by: Jordan Cain <jordan.cain1@uk.ibm.com>
Provide documentation on setting up IDEA when a user only has the community edition.
Doc change
=> Add instructions for IDEA community edition isers

zowe-install/src/main/resources/component-scripts/start.sh
=> Add Cors parameter in the start.sh

CHANGELOG.md
Add changes in version 1.13 to changelog.
=> apiml 1.13 changes

api-catalog-services/build.gradle, discovery-service/build.gradle, gateway-service/build.gradle
Remove deprecated properties to simplify movement towards the Gradle v7
=> Replace deprecated properties with the new ones

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/ApiCatalogController.java, api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocController.java, api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/handlers/ApiCatalogControllerExceptionHandler.java, api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/exceptions/ContainerStatusRetrievalThrowable.java, api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiTransformationConfig.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/ApiCatalogControllerTests.java, common-service-core/src/main/java/org/zowe/apiml/cache/CompositeKey.java, common-service-core/src/main/java/org/zowe/apiml/message/api/ApiMessage.java, common-service-core/src/main/java/org/zowe/apiml/util/ObjectUtil.java, common-service-core/src/test/java/org/zowe/apiml/util/ObjectUtilTest.java, discovery-service/src/main/java/org/zowe/apiml/discovery/staticdef/ServiceDefinitionProcessor.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/SaveZosmfPublicKeyConsoleApplication.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/AuthenticationService.java, gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/SecurityTokenErrorCheckTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/ServiceNotFoundCheckTest.java, integration-tests/src/test/java/org/zowe/apiml/penetration/JwtPenTest.java
The issues are from the SonarCloud technical debt list: https://sonarcloud.io/component_measures?id=zowe_api-layer&metric=sqale_index&view=list
=> Clean smells found by the SonarCube

.run/ApiCatalogApplication.run.xml, .run/DiscoverableClientSampleApplication.run.xml, .run/DiscoveryServiceApplication.run.xml, .run/EnablerV1SampleApplication.run.xml, .run/GatewayApplication.run.xml
store usual run configurations
=> common run configurations

.run/java-Catalog.run.xml, .run/java-DiscoverableClient.run.xml, .run/java-Discovery.run.xml, .run/java-Gateway.run.xml, .run/spring-ApiCatalogApplication.run.xml, .run/spring-DiscoverableClientSampleApplication.run.xml, .run/spring-DiscoveryServiceApplication.run.xml, .run/spring-EnablerV1SampleApplication.run.xml, .run/spring-GatewayApplication.run.xml
Rename of the spring run configs that only enterprise edition of intelli can read
Addition of java run configs for community edition
=> community edition java run configurations

CONTRIBUTING.md
describe branch naming strategy for contributors
=> describe branch naming strategy

CHANGELOG.md
Documentation of the changes in the 1.14 version of the API ML
=> Add key improvements in 1.14 version

integration-tests/src/test/java/org/zowe/apiml/discoveryservice/EurekaInstancesIntegrationTest.java
Return the tests that were considered Flaky but seems to be stable now.
Linked to the issue 692
=> Return to the external environment Eureka related Flaky tests

gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/http/ServiceAuthenticationDecorator.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/dummy/DummyAuthenticationProvider.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/saf/ZosAuthenticationProvider.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/query/QueryFilter.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/AuthenticationService.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/saf/ZosAuthenticationProviderTests.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/query/QueryFilterTest.java, gradle.properties, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/AuthenticationProviders.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/DummyAuthenticationLoginIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/DummyLogoutTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/Login.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/LogoutTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/SafAuthenticationLoginIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/SafLogoutTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/ZosmfAuthenticationLoginIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/ZosmfLogoutTest.java
Update Logout testing to run against the SAF provider. 
Fixes #472 
=> Test Logout functionality against SAF provider

onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidator.java, onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidatorTest.java, onboarding-enabler-java/src/test/resources/bad-ssl-configuration.yml, onboarding-enabler-java/src/test/resources/missing-ssl-configuration.yml, onboarding-enabler-java/src/test/resources/service-configuration-wildcard.yml
=> Fix SSL validation when Eureka is running in HTTP mode

CHANGELOG.md
Added links to the Issues and PRs for the information in Changelog.
Fixes #787
=> Adapt changelog to the new requirements for structure and content.

CHANGELOG.md
Add documentation of changes in the 1.15.0 release.
=> Add Changelog notes for 1.15.0

api-catalog-services/src/main/resources/application.yml, discoverable-client/src/main/resources/application.yml, discoverable-client/src/main/resources/logback.xml, discovery-service/src/main/resources/application.yml, gateway-service/src/main/resources/application.yml
If SSLException occurs it is handled here. There are no other logs in this class.
Fixes #698 
=> log SSLException in DefaultHostnameVerifier

gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/ComponentsConfiguration.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/x509/X509AuthenticationMapper.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/x509/X509AuthenticationProvider.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/x509/X509CommonNameUserMapper.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/x509/X509AuthenticationProviderTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/x509/X509CommonNameUserMapperTest.java
refactor of X509 classes and methods
=> X509 classes refactor

integration-tests/build.gradle, integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogHttpHeadersIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogSecurityIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/discoverableclient/IntegratedZaasClientTest.java, integration-tests/src/test/java/org/zowe/apiml/discoveryservice/EurekaInstancesIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/AuthenticationOnDeploymentTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/GatewaySecurityTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/PassTicketTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/QueryIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/ZosmfSsoIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/DummyAuthenticationLoginIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/DummyLogoutTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/Login.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/LogoutTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/SafAuthenticationLoginIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/SafLogoutTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/ZosmfAuthenticationLoginIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/ZosmfLogoutTest.java, integration-tests/src/test/java/org/zowe/apiml/penetration/JwtPenTest.java, integration-tests/src/test/java/org/zowe/apiml/util/categories/AuthenticationTest.java
run logout tests last on internal pipeline
=> run logout IT last

integration-tests/src/test/java/org/zowe/apiml/gatewayservice/QueryIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/ZosmfSsoIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/ZosmfAuthenticationLoginIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/penetration/JwtPenTest.java, integration-tests/src/test/java/org/zowe/apiml/startup/CheckEnvironment.java
=> fix IT: ZosmfAuthenticationLoginIntegrationTest

gateway-service/src/main/resources/application.yml
=> disable x509 as default

integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/ZosmfAuthenticationLoginIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/startup/CheckEnvironment.java
Isolate users on internal pipeline
Changes need to be made to tests that are coupled to internal pipeline user
=> decouple internal pipelines

CHANGELOG.md
=> Add changelog notes for v1.16.0

CONTRIBUTING.md
Add the description for the Sizing and planning related information. 
Fixes #879
=> Add guidelines around planning and sizing.

CONTRIBUTING.md
=> Update CONTRIBUTING.md - small adjustments around the estimation process

Jenkinsfile, config/local/api-defs/mock-zosmf.yml, config/local/gateway-service.yml, gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/ComponentsConfiguration.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/Providers.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/x509/X509ExternalMapper.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/ProvidersTest.java, integration-tests/src/test/java/org/zowe/apiml/discoverableclient/IntegratedZaasClientTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/SecurityUtils.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/DummyAuthenticationLoginIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/Login.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/SafAuthenticationLoginIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/ZosmfAuthenticationLoginIntegrationTest.java
=> Disable unstable tests on internal pipeline

Jenkinsfile
Publish build of the Caching Service on Jenkins for use by others.
=> Publish build of Caching Service

zowe-install/src/main/resources/component-scripts/start.sh
Part of fixes to fulfill https://github.com/zowe/zowe-install-packaging/issues/1702
=> trap int signal in start script

config/local/gateway-service.yml, gateway-service/src/main/java/org/zowe/apiml/gateway/config/TomcatConfiguration.java, gateway-service/src/main/resources/application.yml, gateway-service/src/test/resources/application-test.yml, gateway-service/src/test/resources/application.yml, integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogEndpointIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/PageRedirectionTest.java, integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReader.java, integration-tests/src/test/java/org/zowe/apiml/util/config/GatewayServiceConfiguration.java, integration-tests/src/test/resources/environment-configuration.yml
Adding another SSL connector for the Gateway. 
Linked to #857
=> Add another configurable SSL port

Jenkinsfile, build.gradle, integration-tests/build.gradle
=> Internal connector integration tests

CHANGELOG.md
Signed-off-by: Andrew Jandacek <andrew.jandacek@broadcom.com>
=> refactor 1.17 changelog feature description

zowe-install/src/main/resources/component-scripts/start.sh
=> Correct zowe debug flag

integration-tests/src/test/java/org/zowe/apiml/cachingservice/CachingApiIntegrationTest.java
=> Run Caching Service integration tests on MF

gradle/publish.gradle
Part of fixes of https://github.com/zowe/zowe-install-packaging/issues/1684. Publishing the discoverable-client jar to Artifactory will help the performance testing tool to pick the dummy service and install onto existing Zowe instance.
=> publish discoverable-client for performance test

caching-service/src/main/java/org/zowe/apiml/caching/service/inmemory/InMemoryStorage.java, integration-tests/src/test/java/org/zowe/apiml/cachingservice/CachingApiIntegrationTest.java
Run multiple insertion and deletion concurrent REST calls and assert that all were recorded correctly. 
=> caching api concurrent integration test

mock-zosmf/src/main/java/org/zowe/apiml/client/api/AuthenticationController.java, zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasHttpsClientProvider.java
These two classes could potentially leak resources, this prevents this behavior.
=> Clean potential resource leaks

common-service-core/src/test/java/org/zowe/apiml/util/MapUtilsTest.java
Clean potentially sensitive terminology from repo.
=> Replace master in the name of key with primary

gateway-service/src/main/java/org/zowe/apiml/gateway/config/GatewayConfig.java, gateway-service/src/main/resources/application.yml, gateway-service/src/test/java/org/zowe/apiml/acceptance/common/AcceptanceTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/config/GatewayConfigTest.java
Eureka client is using port from eureka server configuration if available. Use port from eureka instance.
=> eureka client configuration

common-service-core/src/main/java/org/zowe/apiml/zfile/EnqueueException.java, common-service-core/src/main/java/org/zowe/apiml/zfile/RcException.java, common-service-core/src/main/java/org/zowe/apiml/zfile/ZFile.java, common-service-core/src/main/java/org/zowe/apiml/zfile/ZFileConstants.java, common-service-core/src/main/java/org/zowe/apiml/zfile/ZFileDummyImpl.java, common-service-core/src/main/java/org/zowe/apiml/zfile/ZFileException.java
=> ZFile related interfaces and constants

common-service-core/src/main/java/org/zowe/apiml/util/ClassOrDefaultProxyUtils.java, common-service-core/src/test/java/org/zowe/apiml/util/ClassOrDefaultProxyUtilsTest.java
This pull request brings possibility to request a specific constructor invocation for the proxy utils
=> Proxy mechanism enhancements

gateway-service/src/main/java/org/zowe/apiml/gateway/config/TomcatConfiguration.java, integration-tests/src/test/java/org/zowe/apiml/startup/impl/ApiMediationLayerStartupChecker.java, integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReader.java, integration-tests/src/test/java/org/zowe/apiml/util/config/GatewayServiceConfiguration.java, integration-tests/src/test/java/org/zowe/apiml/util/http/HttpRequestUtils.java, integration-tests/src/test/resources/environment-configuration.yml, integration-tests/src/test/resources/logback.xml
Improve the readability of the logs in the context of the startup checking. Also by default set DEBUG on the test code. 
Linked to #860
=> Improve readability of the startup checker

api-catalog-ui/frontend/cypress/integration/e2e/detail-page/service-version-compare.test.js
e2e tests are failing due to missing text in assertion. Verify actual content of span
=> assert content of span

integration-tests/src/test/java/org/zowe/apiml/gatewayservice/AuthenticationOnDeploymentTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/ServiceHaMode.java, integration-tests/src/test/java/org/zowe/apiml/util/config/RandomPorts.java
The ServiceHA test was using random port but not veryfying that the port was empty. As such it failed occasionally.
=> Use the free port for HA Mode

integration-tests/src/test/java/org/zowe/apiml/cachingservice/CachingApiIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/SecurityUtils.java, integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReader.java, integration-tests/src/test/resources/environment-configuration.yml
Another episode of the Vsam Saga
=> VSAM: enable concurrent test

api-catalog-services/build.gradle, caching-service/build.gradle, discoverable-client/build.gradle, discovery-service/build.gradle, gateway-service/build.gradle, integration-tests/build.gradle, integration-tests/src/test/java/org/zowe/apiml/cachingservice/CachingApiIntegrationTest.java, mock-zosmf/build.gradle
=> Remove previous thin jar impl

apiml-common/build.gradle, apiml-common/src/test/java/org/zowe/apiml/product/gateway/GatewayClientTest.java, apiml-common/src/test/java/org/zowe/apiml/product/gateway/GatewayInstanceInitializerTest.java, apiml-common/src/test/java/org/zowe/apiml/product/instance/lookup/InstanceLookupExecutorTest.java, apiml-common/src/test/java/org/zowe/apiml/product/routing/transform/TransformServiceTest.java, apiml-common/src/test/java/org/zowe/apiml/product/version/VersionServiceTest.java
Updates tests in apiml-common to use JUnit 5.
Fixes #1001 
- [o] I have commented my code, particularly in hard-to-understand areas
- [o] I have made corresponding changes to the documentation
- [o] I have added tests that prove my fix is effective or that my feature works
- [o] Any dependent changes have been merged and published in downstream modules
=> Upgrade tests in apiml-common to use JUnit 5

api-catalog-package/build.gradle, api-catalog-services/build.gradle, caching-service-package/build.gradle, caching-service/build.gradle, discoverable-client/build.gradle, discovery-package/build.gradle, discovery-service/build.gradle, gateway-package/build.gradle, gateway-service/build.gradle
fix publish of springboot components
fix package modules to not include empty jar
This PR will fix issues experienced by master branch
=> Repair publish tasks

api-catalog-package/src/main/resources/bin/start.sh, discovery-package/src/main/resources/bin/start.sh, gateway-package/src/main/resources/bin/start.sh
=> Alter start scripts for the lite packaging

apiml-utility/build.gradle, apiml-utility/src/test/java/org/zowe/apiml/product/logging/ApimlDependencyLogHiderTest.java, apiml-utility/src/test/java/org/zowe/apiml/product/logging/ApimlLogInjectorTest.java, apiml-utility/src/test/java/org/zowe/apiml/product/logging/ApimlRollingFileAppenderTest.java, apiml-utility/src/test/java/org/zowe/apiml/product/logging/LogLevelInfoFilterTest.java, apiml-utility/src/test/java/org/zowe/apiml/product/logging/LogMessageTrackerTest.java, apiml-utility/src/test/java/org/zowe/apiml/product/monitoring/LatencyUtilsConfigInitializerTest.java
Upgrade tests in apiml-utility to JUnit 5
Fixes #1023 
=> Upgrade tests in apiml-utility to JUnit 5

api-catalog-package/src/main/resources/bin/start.sh, discovery-package/src/main/resources/bin/start.sh, gateway-package/src/main/resources/bin/start.sh
Signed-off-by: Jordan Cain <jordan@Jordans-MacBook-Pro.local>
=> Correct location of common lib in start scripts

discoverable-client/src/test/java/org/zowe/apiml/client/api/ApiMediationClientTestControllerTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/api/FileControllerTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/api/GreetingControllerTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/api/GreetingV2ControllerTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/api/MultipartControllerTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/api/PageRedirectionControllerTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/api/PassTicketTestControllerTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/api/PetControllerDeleteTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/api/PetControllerGetAllTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/api/PetControllerGetOneTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/api/PetControllerPostPetTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/api/PetControllerPutTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/api/ZaasClientTestControllerTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/exception/PetIdMismatchExceptionTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/exception/PetNotFoundExceptionTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/impl/PetServiceImplTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/model/GreetingTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/model/PetTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/service/ApiMediationClientServiceTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/ws/WebSocketServerHandlerTest.java
Upgrade tests in discoverable-client to JUnit 5
Fixes #1038 
=> Upgrade tests in discoverable-client to JUnit 5

config/zowe-api-dev/alternative_start.sh, config/zowe-api-dev/run-wrapper.sh, docs/ad-hoc-mainframe-deployment.md, zowe-api.json
Fixes zowe api dev with thin jars and caching service for swift deployment!
=> GH999 zowe-api-dev thin jars update

docs/saf-authorized-endpoints.md
This PR adds developer documentation for PR-1025, PR-1026 and PR-1027.
Fulfill developer documentation.
=> Developer documentation of SAF resource checking via annotation

discovery-service/src/test/java/org/zowe/apiml/discovery/EurekaInstanceCanceledListenerTest.java, discovery-service/src/test/java/org/zowe/apiml/discovery/EurekaInstanceRegisteredListenerTest.java, discovery-service/src/test/java/org/zowe/apiml/discovery/EurekaSecuredEndpointsTest.java, discovery-service/src/test/java/org/zowe/apiml/discovery/GatewayNotifierTest.java, discovery-service/src/test/java/org/zowe/apiml/discovery/metadata/MetadataDefaultsServiceTest.java, discovery-service/src/test/java/org/zowe/apiml/discovery/metadata/MetadataTranslationServiceTest.java, discovery-service/src/test/java/org/zowe/apiml/discovery/staticdef/StaticApiRestControllerTest.java, discovery-service/src/test/java/org/zowe/apiml/discovery/staticdef/StaticServicesRegistrationServiceTest.java, discovery-service/src/test/resources/api-defs-empty/.gitignore
Upgrade tests in discovery-service to JUnit 5
Fixes #1062 
=> Upgrade tests in discovery-service to JUnit 5

gateway-service/build.gradle, gateway-service/src/test/java/org/zowe/apiml/gateway/cache/RetryIfExpiredAspectTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/config/GatewayConfigTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/VersionControllerTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/SecurityErrorCheckTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/ServiceErrorCheckTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/TimeoutErrorCheckTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/filters/post/CustomSendErrorFilterTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/TomcatFilterTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/health/GatewayHealthIndicatorTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/metadata/service/EurekaApplicationsTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/config/CertificateAuthenticationProviderTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/config/CompoundAuthProviderTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/config/JWTLogoutHandlerTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/ProvidersTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/zosmf/JwkToPublicKeyConverterTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfJwkToPublicKeyTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/AuthenticationServiceTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceTest.java
Upgrade tests in gateway-service to JUnit 5
Fixes #1068 
=> Upgrade tests in gateway-service to JUnit 5

onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/impl/ApiMediationClientImplTest.java, onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/util/ApiMediationServiceConfigReaderTest.java, onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/model/DiscoveryInfoTest.java, onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/model/HealthTest.java
Upgrades tests in onboarding-enabler-java to JUnit 5
Fixes #1072
=> Upgrade tests in onboarding-enabler-java to JUnit 5

caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/VsamInitializer.java, caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/VsamStorage.java, caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/config/VsamConfig.java, caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/config/VsamConfiguration.java
to enable multiple caching services to start reliably
=> Add retryable warmup for caching service

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/cached/CachedApiDocService.java, integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogEndpointIntegrationTest.java
Signed-off-by: jordanCain <jordan.cain2@ibm.com>
=> Throw service not found exception during version compare when unable to find instance of service

Jenkinsfile, integration-tests/src/test/java/org/zowe/apiml/cachingservice/CachingApiIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/util/config/AuxiliaryUserList.java, integration-tests/src/test/java/org/zowe/apiml/util/config/Credentials.java, integration-tests/src/test/resources/environment-configuration.yml
Key the users for easier retrieval
=> Enhance IT user provisioning

gateway-package/src/main/resources/bin/start.sh
=> Gateway start script Docker support

security-service-client-spring/src/test/java/org/zowe/apiml/security/client/handler/RestResponseHandlerTest.java, security-service-client-spring/src/test/java/org/zowe/apiml/security/client/login/GatewayLoginProviderTest.java, security-service-client-spring/src/test/java/org/zowe/apiml/security/client/service/GatewaySecurityServiceTest.java, security-service-client-spring/src/test/java/org/zowe/apiml/security/client/token/GatewayTokenProviderTest.java
Upgrades tests in security-service-client-spring to JUnit 5
Fixes #1077 
=> Upgrade tests in security-service-client-spring to JUnit 5

gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/x509/X509AuthenticationProvider.java
=> cleanup unused property

integration-tests/src/test/java/org/zowe/apiml/startup/CheckEnvironment.java
=> Preemptive basic auth in CheckEnvironment

build.gradle, onboarding-enabler-spring/build.gradle, zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientImplHttpTests.java, zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientImplHttpsTests.java, zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasHttpsClientProviderTests.java, zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasJwtServiceTest.java
Upgrade tests in zaas-client to JUnit 5
Fixes #1090 
=> Upgrade tests in zaas-client to JUnit 5

gradle.properties
=> Bump version down to correct 1.20.0-SNAPSHOT

Jenkinsfile, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/ServicesInfoTest.java, integration-tests/src/test/resources/environment-configuration.yml
=> Externalize services info test users

README.md
Minor update to the documentation to prevent some of the issues
=> We using npm but document pnpm

CHANGELOG.md
=> 1.19 changelog

gradle/wrapper/gradle-wrapper.properties
=> use latest version of gradle

caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/VsamFile.java, caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/VsamInitializer.java, caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/ZFileProducer.java, caching-service/src/test/java/org/zowe/apiml/caching/service/vsam/DefaultVsamConfiguration.java, caching-service/src/test/java/org/zowe/apiml/caching/service/vsam/VsamFileTest.java, caching-service/src/test/java/org/zowe/apiml/caching/service/vsam/VsamInitializerTest.java, caching-service/src/test/java/org/zowe/apiml/caching/service/vsam/ZFileProducerTest.java
There were no unit tests for VsamFile. This PR is fixing this. 
Linked to #998
=> VsamFile unit tests and related refactoring

CONTRIBUTING.md
Add missing mock zOSMF module to the CONTRIBUTING guideline. 
Linked to #967
=> Improve the Contributing with info about the mock zOSMF

onboarding-enabler-nodejs-sample-app/README.md, onboarding-enabler-nodejs-sample-app/package.json, onboarding-enabler-nodejs-sample-app/src/index.js, onboarding-enabler-nodejs/README.md, onboarding-enabler-nodejs/package.json, scripts/publish_and_release.sh
=> Publish Node.js enabler as part of the API ML release

.github/pull_request_template.md, CONTRIBUTING.md
Update of contributing guideline with commit template. Has no functional effect for now, may be used in future for automation. 
Fixes #1184 
=> Introduce commit message template

common-service-core/src/main/java/org/zowe/apiml/util/UrlUtils.java
=> Ignoring incorrect warning

scripts/publish_and_release.sh
Issue has been opened to repair them. 
=> temporally remove broken release types

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/TransformApiDocService.java, api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiTransformationConfig.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/TransformApiDocServiceTest.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/ApiTransformationConfigTest.java
Accept swagger/openapi documents in yaml format.
Fixes #1182 
=> fix: accept swagger/openapi in yaml format

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/cached/CachedApiDocService.java, caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/VsamFile.java, discovery-service/src/main/java/org/zowe/apiml/discovery/staticdef/ServiceDefinitionProcessor.java, gateway-service/src/main/java/org/zowe/apiml/gateway/metadata/service/LoadBalancerRegistry.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/ApimlX509Filter.java, onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidator.java, onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidatorTest.java
Fixes six critical code smells from Sonar's report
Fixes #1132
=> Fixing critical sonar code smells

scripts/publish_and_release.sh
chore: Disable javascript enabler publish
=> Disable javascript enabler publish

.gitignore, common-service-core/src/test/java/org/zowe/apiml/security/SecurityUtilsTest.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/JwtSecurityInitializer.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/ProvidersTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/JwtSecurityInitializerTest.java
The code for removal of the requirement for the JWT secret was integrated with limited test coverage. This is fix. 
Fixes #970
=> Improve test coverage for the JWT secret

gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/JwtSecurityInitializer.java
=> Properly provide the default duration

onboarding-enabler-nodejs-sample-app/src/index.js, onboarding-enabler-nodejs/README.md, onboarding-enabler-nodejs/src/index.js
=> Add unregistration method to Node.js enabler

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/model/APIService.java, api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/cached/CachedProductFamilyService.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/ApiCatalogControllerTests.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/status/ApiServiceStatusServiceTest.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/util/ContainerServiceMockUtil.java
Refactors `org.zowe.apiml.apicatalog.model.APIService` constructor implementing flowing build.
Partially fixes #1132
=> APIService flowing builder

scripts/publish_and_release.sh
=> chore: Dont test while releasing

build.gradle
=> chore: Try removing buildTasks

gateway-service/src/test/java/org/zowe/apiml/acceptance/ForwardedProxyHeadersTest.java, gateway-service/src/test/java/org/zowe/apiml/acceptance/RetryPerServiceTest.java, gateway-service/src/test/java/org/zowe/apiml/acceptance/TimeoutPerServiceTest.java
=> Disable specific tests

Jenkinsfile, caching-service/build.gradle, caching-service/src/main/java/org/zowe/apiml/caching/api/CachingController.java, caching-service/src/main/java/org/zowe/apiml/caching/service/Messages.java, caching-service/src/main/resources/application.yml, caching-service/src/main/resources/caching-log-messages.yml, caching-service/src/test/java/org/zowe/apiml/caching/api/CachingControllerTest.java, integration-tests/src/test/java/org/zowe/apiml/cachingservice/CachingApiIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/cachingservice/RejectEvictionTest.java, integration-tests/src/test/java/org/zowe/apiml/cachingservice/RemoveOldestTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/LoginTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/X509SchemeTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/ZosmfAuthenticationLoginTest.java, integration-tests/src/test/java/org/zowe/apiml/util/CachingRequests.java, integration-tests/src/test/java/org/zowe/apiml/util/config/SslContext.java, integration-tests/src/test/resources/environment-configuration.yml
=> Replace JWT with client cert in caching service

caching-service/build.gradle, caching-service/src/main/java/org/zowe/apiml/caching/config/SpringSecurityConfig.java, caching-service/src/main/resources/application.yml, integration-tests/src/test/java/org/zowe/apiml/cachingservice/WebSecurityTest.java, integration-tests/src/test/java/org/zowe/apiml/gatewayservice/SecurityUtils.java, integration-tests/src/test/java/org/zowe/apiml/util/service/DiscoveryUtils.java
=> Introduce spring security for caching service

build.gradle
=> Update sonar plugin

gateway-service/src/test/java/org/zowe/apiml/acceptance/ForwardedProxyHeadersTest.java, gateway-service/src/test/java/org/zowe/apiml/acceptance/RetryPerServiceTest.java, gateway-service/src/test/java/org/zowe/apiml/acceptance/TimeoutPerServiceTest.java
=> chore: Enable acceptance tests again

gateway-service/src/test/java/org/zowe/apiml/acceptance/TimeoutPerServiceTest.java
=> Disable failing tests for release

common-service-core/src/main/java/org/zowe/apiml/util/UrlUtils.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/saf/MockPlatformUser.java
Attends some of the security hotspots that Sonar reports.
=> Sonar - some Security Hotspots

.gitignore
Add git ignore for the api-layer/onboarding-enabler-nodejs-sample-app/tools
Linked to #N/A
=> Gitignore api-layer/onboarding-enabler-nodejs-sample-app/tools

docs/release.md
Add a couple notes to steps experienced in last release process.
=> Add notes to release process

apiml-common/src/main/java/org/zowe/apiml/product/security/WebServerSecurityConfig.java, apiml-security-common/src/main/java/org/zowe/apiml/security/common/config/AuthConfigurationProperties.java, apiml-security-common/src/test/java/org/zowe/apiml/security/common/token/QueryResponseTest.java, apiml-utility/src/main/java/org/zowe/apiml/product/logging/ApimlLogInjector.java, common-service-core/src/main/java/org/zowe/apiml/message/core/AbstractMessageService.java, common-service-core/src/main/java/org/zowe/apiml/passticket/AbstractIRRPassTicketException.java, common-service-core/src/main/java/org/zowe/apiml/util/ClassOrDefaultProxyUtils.java, common-service-core/src/main/java/org/zowe/apiml/util/MapUtils.java, common-service-core/src/main/java/org/zowe/apiml/util/ObjectUtil.java, common-service-core/src/main/java/org/zowe/apiml/util/UrlUtils.java, common-service-core/src/test/java/org/zowe/apiml/util/ClassOrDefaultProxyUtilsTest.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/X509Scheme.java
Fixes some code smells from sonar
=> Fixing sonar code smells

gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/saf/ZosAuthenticationProvider.java
=> fix: value injection syntax

.github/workflows/sonarqube.yml
=> chore: Add Github Token needed for master branch run

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV2Service.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV2ServiceTest.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3ServiceTest.java
Handle Swagger v2 in yaml format.
Fixes #1229 
=> Fix: Swagger v2 yaml parsed and rendered

.github/workflows/snapshot-release.yml, Jenkinsfile
=> chore: Move Snapshot release to GH Actions

.github/workflows/release.yml, .github/workflows/specific-release.yml
=> chore: GH Actions authenticate as different user

.github/workflows/release.yml, .github/workflows/specific-release.yml
=> chore: Add PAT

.github/workflows/codeql.yml
=> chore: Add Code QL to get the security inputs

.github/workflows/ci-internal-tests.yml, .github/workflows/ci-tests-with-rsu2012.yml, .github/workflows/ci-tests-without-jwt-with-authenticate.yml, .github/workflows/ci-tests-without-jwt.yml, .github/workflows/ci-tests.yml, .github/workflows/codeql.yml, .github/workflows/release.yml, .github/workflows/snapshot-release.yml, .github/workflows/sonarqube.yml, .github/workflows/specific-release.yml
=> chore: Add timeouts to the GH Actions

.github/workflows/release.yml, .github/workflows/specific-release.yml, onboarding-enabler-nodejs/.npmrc
=> chore: Release the NPM libraries as part of the release process.

.github/workflows/release.yml, .github/workflows/specific-release.yml
=> chore: commit before release

.github/workflows/release.yml, .github/workflows/specific-release.yml, build.gradle, onboarding-enabler-nodejs/package.json
=> chore: Updated release procedure

.github/pull_request_template.md, CONTRIBUTING.md
=> more specific template

gateway-package/src/main/resources/bin/start.sh
=> chore: https zss

caching-service/src/test/java/org/zowe/apiml/caching/api/CachingControllerTest.java, caching-service/src/test/java/org/zowe/apiml/caching/service/inmemory/InMemoryStorageTest.java, caching-service/src/test/java/org/zowe/apiml/caching/service/vsam/EvictionStrategyProducerTest.java, caching-service/src/test/java/org/zowe/apiml/caching/service/vsam/RemoveOldestStrategyTest.java, caching-service/src/test/java/org/zowe/apiml/caching/service/vsam/VsamInitializerTest.java, caching-service/src/test/java/org/zowe/apiml/caching/service/vsam/VsamStorageTest.java, caching-service/src/test/java/org/zowe/apiml/caching/service/vsam/ZFileProducerTest.java
=> refactor: Refactor tests to use Nested pattern

gateway-package/src/main/resources/bin/start.sh, zss-sample-service/server.js
=> chore: do not override external mapper url in script

caching-service/src/main/java/org/zowe/apiml/caching/api/CachingController.java, caching-service/src/test/java/org/zowe/apiml/caching/api/CachingControllerTest.java, integration-tests/build.gradle
=> feat: Caching service: Remove key alphanumeric constraint

api-catalog-package/src/main/resources/bin/start.sh, api-catalog-package/src/main/resources/bin/validate.sh, caching-service-package/src/main/resources/bin/start.sh, caching-service-package/src/main/resources/bin/validate.sh, discovery-package/src/main/resources/bin/start.sh, discovery-package/src/main/resources/bin/validate.sh, gateway-package/src/main/resources/bin/start.sh, gateway-package/src/main/resources/bin/validate.sh
=> Remove wait from start.sh to reduce address spaces

api-catalog-ui/frontend/src/components/Error/ErrorFormatter.jsx, api-catalog-ui/frontend/src/components/ErrorBoundary/BigShield/BigShield._test.jsx, api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.jsx
Refactors code to resolve critical issues reported by Sonar
=> API Catalog UI fix critical issues from Sonar report

gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/HeaderSanitizerFilter.java, gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/HeaderSanitizerFilterTest.java
=> fix: stop leaking of X-Certificate headers

api-catalog-ui/frontend/src/actions/service-version-diff-actions.jsx, api-catalog-ui/frontend/src/components/App/App.jsx, api-catalog-ui/frontend/src/components/Swagger/Swagger.jsx, api-catalog-ui/frontend/src/reducers/authentication-reducer.jsx, api-catalog-ui/frontend/src/reducers/fetch-tile-reducer.jsx, api-catalog-ui/frontend/src/reducers/filter-reducer.jsx, api-catalog-ui/frontend/src/reducers/loading-reducer.jsx, api-catalog-ui/frontend/src/reducers/refresh-static-apis-reducer.jsx, api-catalog-ui/frontend/src/reducers/selected-service-reducer.jsx, api-catalog-ui/frontend/src/reducers/service-version-diff-reducer.jsx, api-catalog-ui/frontend/src/setupTests.js
Refactors the code to resolve major issues reported by sonar on the catalog ui.
=> Fix major issues from Sonar in Catalog UI

api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/ApiCatalogControllerContainerRetrievalTest.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocControllerApiDocNotFoundTest.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocControllerServiceNotFoundTest.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIRefreshControllerTest.java, apiml-common/build.gradle, discoverable-client/build.gradle, discoverable-client/src/main/resources/application.yml, discoverable-client/src/test/java/org/zowe/apiml/client/api/FileControllerTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/api/GreetingControllerTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/api/GreetingV2ControllerTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/api/PageRedirectionControllerTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/api/PassTicketTestControllerTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/api/PetControllerDeleteTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/api/PetControllerGetAllTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/api/PetControllerGetOneTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/api/PetControllerPostPetTest.java, discoverable-client/src/test/java/org/zowe/apiml/client/api/PetControllerPutTest.java, discovery-service/build.gradle, gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceTest.java, gradle/versions.gradle, integration-tests/src/test/java/org/zowe/apiml/startup/impl/ApiMediationLayerStartupChecker.java, integration-tests/src/test/java/org/zowe/apiml/ws/WebSocketProxyTest.java
Moving to a supported version of Spring Boot. 
Linked to #1352
=> chore: Upgrade Spring Boot to 2.3 version

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/security/SecurityConfiguration.java, caching-service/src/main/java/org/zowe/apiml/caching/config/SpringSecurityConfig.java, discovery-service/src/main/java/org/zowe/apiml/discovery/config/AbstractWebSecurityConfigurer.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/SecurityConfiguration.java
Disable sonar checks for CSRF
Linked to #1132 
=> Remove outstanding security hotspots reported by sonar

caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/VsamFile.java, caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/VsamInitializer.java, caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/VsamStorage.java, discoverable-client/src/test/java/org/zowe/apiml/client/model/PetTest.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/SaveZosmfPublicKeyConsoleApplication.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/AbstractZosmfService.java, gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/LocationFilterTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/AuthenticationServiceTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/AuthenticationSchemeFactoryTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ZosmfSchemeTest.java, integration-tests/src/test/java/org/zowe/apiml/discoveryservice/EurekaInstancesIntegrationTest.java, onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/EurekaClientProvider.java, onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/impl/ApiMediationClientImpl.java, onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/impl/ZUtil.java, onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/impl/ZUtilDummy.java, onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidatorTest.java
Code refactoring to resolve miscellaneous major issues reported by Sonar
=> Fixing miscellaneous major issues reported by Sonar

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/cached/CachedProductFamilyService.java
=> fix: filter api info without apiId

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/handlers/NotFoundErrorController.java, api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/instance/InstanceRetrievalService.java, caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/VsamFile.java, caching-service/src/test/java/org/zowe/apiml/caching/service/inmemory/InMemoryStorageTest.java, common-service-core/src/main/java/org/zowe/apiml/message/api/ApiMessage.java, discoverable-client/src/main/java/org/zowe/apiml/client/api/MultipartController.java, discoverable-client/src/test/java/org/zowe/apiml/client/api/X509ControllerTest.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfJwkToPublicKey.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZosmfScheme.java, gateway-service/src/main/java/org/zowe/apiml/gateway/ws/GatewayWebSocketConfigurer.java, gateway-service/src/test/java/org/zowe/apiml/acceptance/ForwardedProxyHeadersTest.java, gateway-service/src/test/java/org/zowe/apiml/acceptance/RetryPerServiceTest.java, gateway-service/src/test/java/org/zowe/apiml/acceptance/TimeoutPerServiceTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/TimeoutErrorCheckTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/AuthenticationSchemeFactoryTest.java, integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogEndpointIntegrationTest.java, security-service-client-spring/src/test/java/org/zowe/apiml/security/client/service/GatewaySecurityServiceTest.java
Once more some refactoring to fix issues reported by Sonar
=> Miscellaneous refactoring for Sonar issues

caching-service/src/main/java/org/zowe/apiml/caching/service/inmemory/RemoveOldestStrategy.java, gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketRoutedSession.java
Remove irrelevant condition
Linked to #1132 
=> chore: Fix SC bug and major issue

CHANGELOG.md
=> chore: Add key features and bug fixes to the changelog.

integration-tests/README.md
=> docs: Explain how to run API ML with starting services outside of the IT

README.md, apiml-common-lib-package/build.gradle, apiml-common-lib-package/src/main/update_apiml.sh, scripts/README.md, scripts/update_apiml.sh
=> Script to update apiml

CHANGELOG.md
=> chore: Remove feature which will be available in 1.22

gateway-service/src/main/java/org/zowe/apiml/gateway/config/GatewayConfig.java
Change the hostname used in instance id. 
Linked to #1426
=> fix: Use actual hostname instead of the one provided by the Spring Cloud

.github/workflows/security-analysis.yml, scripts/security_sensitive/index.js, scripts/security_sensitive/package.json
We want to be aware of PRs that are touching security-related areas of the code to invest more effort in review.  
Linked to #1123
=> refactor: Identify and mark security related PRs

gateway-package/src/main/resources/bin/start.sh
Use PKCS11_TOKEN_LABEL from zowe installation if this variable is available. 
Linked to #1410 
=> fix: configurable jwt alias at startup

certificate-analyser/build.gradle
Name of main class has been changed but this was not reflected in gradle build.
=> fix: change name of main class

api-catalog-services/src/main/resources/apicatalog-log-messages.yml, apiml-security-common/src/main/resources/security-common-log-messages.yml, common-service-core/src/main/resources/core-log-messages.yml, gateway-service/src/test/resources/gateway-messages.yml, scripts/docs/index.js, zaas-client/src/main/resources/zaas-client-log-messages.yml
Signed-off-by: Andrew Jandacek <andrew.jandacek@broadcom.com>
=> refactor error code messages

CONTRIBUTING.md
=> chore: Adjust testing guidelines

api-catalog-ui/frontend/src/actions/user-actions.jsx, api-catalog-ui/frontend/src/epics/fetch-tiles.jsx, api-catalog-ui/frontend/src/services/user.service.jsx
=> Allow customised SSO in Catalog

api-catalog-ui/frontend/package-lock.json, api-catalog-ui/frontend/package.json, package-lock.json
=> fix: Fix npm vulnerabilities

api-catalog-services/src/main/resources/application.yml, discovery-service/src/main/resources/application.yml
Update the instance id for the API Catalog and Discovery service. 
Linked to #1426
=> Change the registration to use the correct hostname in instanceId

build.gradle, docs/release.md
=> Remove the need to release from master branch

integration-tests/src/test/java/org/zowe/apiml/functional/gateway/VersionTest.java
Add functional test for all the ways to access the version endpoint. 
Linked to #1458
=> Return functional test for Version endpoint

integration-tests/src/test/java/org/zowe/apiml/functional/gateway/GatewayTimeoutTest.java, integration-tests/src/test/java/org/zowe/apiml/startup/impl/ApiMediationLayerStartupChecker.java, integration-tests/src/test/java/org/zowe/apiml/util/service/FullApiMediationLayer.java
Look into options to shorten the startup time for the integration tests. 
Linked to #1415
=> Remove random waiting time.

certificate-analyser/src/main/java/org/zowe/apiml/Analyser.java, certificate-analyser/src/main/java/org/zowe/apiml/LocalHandshake.java, certificate-analyser/src/main/java/org/zowe/apiml/VerifierSSLContext.java, certificate-analyser/src/test/java/org/zowe/apiml/AnalyserTest.java, certificate-analyser/src/test/java/org/zowe/apiml/LocalHandshakeTest.java, certificate-analyser/src/test/java/org/zowe/apiml/RemoteHandshakeTest.java
=> fix: remote call without client certificate

metrics-service/build.gradle
Fix metrics service publishing.
=> Fix: metrics service publishing

build.gradle
=> chore: se any branch

gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/dummy/DummyAuthenticationProvider.java
=> fix: dummy auth 

.github/workflows/changelog.yml, scripts/release_docs/index.js, scripts/release_docs/package.json
Add manually run action which generates features and fixes based on the conventional commits and prepare PR with the changes.
Linked to #1444
=> Automate generation of Changelog via GH action

apiml-security-common/src/main/java/org/zowe/apiml/security/common/login/LoginRequest.java, apiml-security-common/src/test/java/org/zowe/apiml/security/common/login/LoginRequestTest.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/saf/ZosAuthenticationProvider.java, integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/PassticketSchemeTest.java, integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReader.java
Fixing issues revealed in testing on mainframe 
=> fix: integration tests fails 

CHANGELOG.md
Update changelog for new release
=> Add release 1.22 changelog

integration-tests/build.gradle, integration-tests/src/test/java/org/zowe/apiml/integration/zos/ServicesInfoTest.java
=> chore: do login only when needed

.github/workflows/docs.yml, scripts/docs/index.js
=> chore: Run once a week th script for error messages

.github/workflows/containers.yml, gradle/jib.gradle
Overlooked the pattern in case started from master branch. 
Linked to #1361
=> Don't use PR in master build

common-service-core/build.gradle, gradle/versions.gradle, onboarding-enabler-java/build.gradle
=> Upgrade Eureka version

.run/Analyser.run.xml, certificate-analyser/src/main/java/org/zowe/apiml/Analyser.java, certificate-analyser/src/main/java/org/zowe/apiml/ApimlConf.java, certificate-analyser/src/main/java/org/zowe/apiml/LocalHandshake.java, certificate-analyser/src/main/java/org/zowe/apiml/LocalVerifier.java, certificate-analyser/src/main/java/org/zowe/apiml/RemoteHandshake.java, certificate-analyser/src/main/java/org/zowe/apiml/Stores.java, certificate-analyser/src/main/java/org/zowe/apiml/VerifierSSLContext.java, certificate-analyser/src/main/java/org/zowe/apiml/server/SocketServer.java, certificate-analyser/src/test/java/org/zowe/apiml/RemoteHandshakeTest.java, certificate-analyser/src/test/java/org/zowe/apiml/StoresTest.java
update certificate analyser functionality as a part of troubleshooting guide
=> refactor: cert analyser update

config/docker/gateway-service.yml, gateway-service/src/main/resources/application.yml, gateway-service/src/test/java/org/zowe/apiml/acceptance/ForwardedProxyHeadersTest.java, gateway-service/src/test/java/org/zowe/apiml/acceptance/RequestInstanceTest.java, gateway-service/src/test/java/org/zowe/apiml/acceptance/RetryPerServiceTest.java, gateway-service/src/test/java/org/zowe/apiml/acceptance/TimeoutPerServiceTest.java, gateway-service/src/test/java/org/zowe/apiml/acceptance/common/AcceptanceTest.java, gateway-service/src/test/java/org/zowe/apiml/acceptance/corsTests/CorsPerServiceTest.java, gateway-service/src/test/java/org/zowe/apiml/acceptance/corsTests/GatewayCorsEnabledTest.java, gateway-service/src/test/resources/application-test.yml, gateway-service/src/test/resources/application.yml, integration-tests/src/test/java/org/zowe/apiml/util/requests/GatewayRequests.java, integration-tests/src/test/java/org/zowe/apiml/util/requests/Requests.java
Fix and enable acceptance tests. 
Linked to #1421
=> chore: Enable acceptance tests

gateway-service/src/main/java/org/zowe/apiml/gateway/routing/ApimlRoutingConfig.java, gateway-service/src/main/java/org/zowe/apiml/gateway/routing/FilterConfig.java, gateway-service/src/test/java/org/zowe/apiml/acceptance/config/ApimlRoutingConfig.java
Make sure we limit the changes of configuration in the functional tests to the minimum. Improve code coverage. 
Linked to #1421
=> chore: Move filter configuration to separate config class

gradle/versions.gradle
Upgrade patch versions of dependencies in preparation for 1.23 release.
=> chore: Clean and upgrade versions

.github/workflows/containers.yml, caching-service/src/main/java/org/zowe/apiml/caching/service/redis/config/RedisConfig.java, caching-service/src/main/java/org/zowe/apiml/caching/service/redis/config/RedisConfiguration.java, caching-service/src/main/resources/application.yml, caching-service/src/test/java/org/zowe/apiml/caching/service/redis/config/RedisConfigTest.java, caching-service/src/test/java/org/zowe/apiml/caching/service/redis/config/RedisConfigurationTest.java
Improves how the redis configuration for the caching service can be externalized.
Linked to #1588 
=> fix: Improve redis configuration for users

api-catalog-services/src/main/resources/apicatalog-log-messages.yml
Signed-off-by: Andrew Jandacek <andrew.jandacek@broadcom.com>
=> language refactor of api catalog log messages

docker/README.md, docker/ha-local/docker-compose.yml
High Availability Docker Compose. 
Linked to #1537
=> Add HA setup for Docker

api-catalog-ui/frontend/src/actions/wizard-actions.jsx, api-catalog-ui/frontend/src/actions/wizard-actions.test.jsx, api-catalog-ui/frontend/src/components/Wizard/WizardDialog.jsx, api-catalog-ui/frontend/src/components/Wizard/WizardDialog.test.jsx, api-catalog-ui/frontend/src/components/Wizard/WizardInputs.jsx, api-catalog-ui/frontend/src/components/Wizard/WizardInputs.test.jsx, api-catalog-ui/frontend/src/components/Wizard/WizardInputsContainer.jsx, api-catalog-ui/frontend/src/components/Wizard/WizardNavigation.jsx, api-catalog-ui/frontend/src/components/Wizard/WizardNavigation.test.jsx, api-catalog-ui/frontend/src/components/Wizard/WizardNavigationContainer.jsx, api-catalog-ui/frontend/src/components/Wizard/wizard_config.jsx, api-catalog-ui/frontend/src/constants/wizard-constants.jsx, api-catalog-ui/frontend/src/reducers/wizard-reducer.jsx, api-catalog-ui/frontend/src/reducers/wizard-reducer.test.jsx
Separated different logic into different components to improve modularity.
Linked to #1370
=> refactor: Wizard logic separation

gateway-service/src/main/resources/application.yml
=> fix: http in swagger url

api-catalog-ui/frontend/src/components/Wizard/WizardNavigation.jsx, api-catalog-ui/frontend/src/components/Wizard/WizardNavigation.test.jsx
Signed-off-by: ViktorKorladinov <v.korladinov@gmail.com>
Fixed a problem with handling changes from input fields in the wizard dialog.
Linked to #1370 
=> fix: Wizard input hotfix

apiml-common/build.gradle, apiml-common/src/main/resources/logback.xml, gradle/versions.gradle
Disables logging filters when running in debug or dev or diag modes. Can be extended to other services.
=> feat: Conditional full debug logging for apiml common

api-catalog-package/src/main/resources/bin/start.sh, caching-service-package/src/main/resources/bin/start.sh, discovery-package/src/main/resources/bin/start.sh, gateway-package/src/main/resources/bin/start.sh
Related to AT-TLS story. Components need to know where the native library is. 
Linked to #1347 
=> feat: path to a native java library

apiml-common/src/main/java/org/zowe/apiml/product/web/HttpConfig.java
=> do not include ciphers

gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/AbstractAuthenticationScheme.java, gateway-service/src/test/java/org/zowe/apiml/acceptance/DeterministicUserBasedRoutingTest.java, gateway-service/src/test/java/org/zowe/apiml/acceptance/common/AcceptanceTestWithBasePath.java, gateway-service/src/test/java/org/zowe/apiml/acceptance/corsTests/GatewaySpecificEndpointsCorsDisabledTest.java, gateway-service/src/test/java/org/zowe/apiml/acceptance/requests/SecurityRequests.java
Clean the tests around the SAF IDT implementation area. 
Linked to #1627
=> refactor: Cleanup before actual implementation

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/security/SecurityConfiguration.java, apiml-tomcat-common/src/main/java/org/zowe/apiml/filter/AttlsEnabledFilter.java, apiml-tomcat-common/src/main/java/org/zowe/apiml/filter/AttlsFilter.java, apiml-tomcat-common/src/main/java/org/zowe/apiml/filter/SecureConnectionFilter.java, apiml-tomcat-common/src/test/java/org/zowe/apiml/filter/AttlsFilterTest.java, apiml-tomcat-common/src/test/java/org/zowe/apiml/filter/SecureConnectionFilterTest.java, caching-service/src/main/java/org/zowe/apiml/caching/config/SpringSecurityConfig.java, discovery-service/src/main/java/org/zowe/apiml/discovery/config/HttpsWebSecurityConfig.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/NewSecurityConfiguration.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/SecurityConfiguration.java, gradle/versions.gradle
Add a filter that will verify whether the connection is secure 
Linked to #1347 
=> fix: prevent API ML run with unsecure connection

api-catalog-ui/frontend/package-lock.json, api-catalog-ui/frontend/package.json, package-lock.json
=> chore: Fix npm vulnerabilities

.github/workflows/release.yml, .github/workflows/snapshot-release.yml, .github/workflows/specific-release.yml, gradle.properties, onboarding-enabler-nodejs/package.json
=> fix: udpate npm in actions

config/zowe-api-dev/alternative_start.sh, config/zowe-api-dev/run-wrapper.sh
Update zowe-api-dev with latest start scripts and variables
=> chore: zowe-api-dev update

.github/workflows/containers.yml, config/docker/api-catalog-services.yml, docker/nginx/conf/load-balancer.conf, integration-tests/src/test/java/org/zowe/apiml/integration/ha/ApiCatalogMultipleInstancesTest.java, integration-tests/src/test/java/org/zowe/apiml/util/config/ApiCatalogServiceConfiguration.java, integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReader.java, integration-tests/src/test/java/org/zowe/apiml/util/config/DiscoverableClientConfiguration.java, integration-tests/src/test/java/org/zowe/apiml/util/requests/ApiCatalogRequests.java, integration-tests/src/test/java/org/zowe/apiml/util/requests/Apps.java, integration-tests/src/test/java/org/zowe/apiml/util/requests/ha/HAApiCatalogRequests.java, integration-tests/src/test/resources/environment-configuration-attls.yml, integration-tests/src/test/resources/environment-configuration-docker.yml, integration-tests/src/test/resources/environment-configuration-ha.yml, integration-tests/src/test/resources/environment-configuration.yml
* Add Nginx and Docker configuration in GH actions to start second instances of DC and AC.
* Add HA tests for API Catalog
Linked to #1584 
=> chore: Create HA tests for API Catalog

config/docker/api-defs/staticclient.yml, config/docker/gateway-service.yml, config/local/api-defs-http/staticclient.yml, config/local/api-defs/staticclient.yml, config/local/gateway-service.yml, integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/SafIdtSchemeTest.java, integration-tests/src/test/java/org/zowe/apiml/util/requests/GatewayRequests.java, integration-tests/src/test/java/org/zowe/apiml/util/requests/Requests.java
Provide integration test and related setup for the functionality. 
Linked to #1629
=> chore: Add Integration test for SAF IDT scheme

.github/workflows/containers.yml, discoverable-client/src/main/resources/application.yml, integration-tests/src/test/java/org/zowe/apiml/integration/ha/SouthboundServiceChaoticTest.java, integration-tests/src/test/java/org/zowe/apiml/integration/ha/SouthboundServiceMultipleInstancesTest.java, integration-tests/src/test/java/org/zowe/apiml/integration/ha/WebSocketChaoticTest.java, integration-tests/src/test/java/org/zowe/apiml/integration/ha/WebSocketMultipleInstancesTest.java, integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReader.java, integration-tests/src/test/java/org/zowe/apiml/util/config/DiscoverableClientConfiguration.java, integration-tests/src/test/java/org/zowe/apiml/util/requests/DiscoverableClientRequests.java, integration-tests/src/test/java/org/zowe/apiml/util/requests/GatewayRequests.java, integration-tests/src/test/java/org/zowe/apiml/util/requests/ha/HADiscoverableClientRequests.java, integration-tests/src/test/java/org/zowe/apiml/util/requests/ha/HAGatewayRequests.java, integration-tests/src/test/resources/environment-configuration-attls.yml, integration-tests/src/test/resources/environment-configuration-docker.yml, integration-tests/src/test/resources/environment-configuration-ha.yml, integration-tests/src/test/resources/environment-configuration.yml
Add IT to test HA setup for DC and WebSocket 
Linked to #1638
=> chore: Add Chaotic tests for southbound service + Websocket tests

gateway-service/src/main/resources/gateway-log-messages.yml
=> chore: explain override to startup timeout

.run/spring-ApiCatalogApplication.run.xml, config/docker/discovery-service.yml, config/local/gateway-service.yml, discovery-service/build.gradle, discovery-service/src/main/resources/application.yml, discovery-service/src/test/java/org/zowe/apiml/discovery/functional/DiscoveryFunctionalTest.java, discovery-service/src/test/java/org/zowe/apiml/discovery/functional/HttpSecuredEndpointTest.java, discovery-service/src/test/java/org/zowe/apiml/discovery/functional/HttpsSecuredEndpointsTest.java, discovery-service/src/test/resources/application.yml, integration-tests/build.gradle, integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogAuthenticationTest.java, integration-tests/src/test/java/org/zowe/apiml/functional/caching/CachingAuthenticationTest.java, integration-tests/src/test/java/org/zowe/apiml/functional/discovery/EurekaInstancesIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/functional/gateway/StaticClientRoutingEndpointsTest.java, integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/LoginTest.java, integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/RefreshTest.java, integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/ZosmfLoginTest.java, integration-tests/src/test/java/org/zowe/apiml/integration/authentication/schemes/X509SchemeTest.java, integration-tests/src/test/java/org/zowe/apiml/integration/discovery/DiscoveryAuthIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/integration/external/CachingStorageTest.java, integration-tests/src/test/java/org/zowe/apiml/integration/zos/ServicesInfoTest.java, integration-tests/src/test/java/org/zowe/apiml/util/config/ItSslConfigFactory.java, integration-tests/src/test/java/org/zowe/apiml/util/config/SslContext.java, integration-tests/src/test/java/org/zowe/apiml/util/config/SslContextConfigurer.java, integration-tests/src/testFixtures/java/org/zowe/apiml/util/config/SslContext.java, integration-tests/src/testFixtures/java/org/zowe/apiml/util/config/SslContextConfigurer.java
=> refactor: Discovery service functional test infrastructure

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticDefinitionController.java, api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticDefinitionGenerator.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/staticapi/StaticDefinitionControllerTest.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/staticapi/StaticDefinitionGeneratorTest.java, integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogEndpointIntegrationTest.java
=> feat: possibility to delete static def

.github/workflows/merge-major-version.yml
=> Add action to merge major version

.github/workflows/merge-major-version.yml, api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/cached/CachedProductFamilyService.java, apiml-common/src/main/java/org/zowe/apiml/product/routing/transform/TransformService.java
Limit the cases where the Catalog fails without any information. 
Linked to #1554
=> Handle errors in apiversions and wrong URLs

.github/workflows/create-image-without-release.yml
Signed-off-by: Adarshdeep Cheema <adarshdeep.cheema@ibm.com>
Linked to # (issue) https://github.com/zowe/api-layer/issues/1786
=> chore: Option for creating specific service test image

caching-service/src/main/java/org/zowe/apiml/caching/service/redis/config/RedisConfig.java, caching-service/src/main/java/org/zowe/apiml/caching/service/redis/config/RedisConfiguration.java
=> chore: create redis config beans conditionally

CONTRIBUTING.md
=> chore: security fixes guideline

docs/websockets.md, onboarding-enabler-nodejs/README.md
updating the documentation to reflect the change in /zowe/api-layer/pull/1813
Signed-off-by: Adarshdeep Cheema <adarshdeep.cheema@ibm.com>
Linked to # (issue) https://github.com/zowe/api-layer/issues/1173
=> updating the documentation to reflect the change in #1813

gradle/lite.gradle, gradle/sonar.gradle, onboarding-enabler-java-sample-app-plain-java/build.gradle, onboarding-enabler-java-sample-app-plain-java/config/service-configuration.yml, onboarding-enabler-java-sample-app-plain-java/readme.md, onboarding-enabler-java-sample-app-plain-java/src/main/java/org/zowe/apiml/sample/PlainJavaEnablerApp.java, onboarding-enabler-java-sample-app/build.gradle, onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidator.java, onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidatorTest.java, onboarding-enabler-java/src/test/resources/service-configuration-keyring.yml, settings.gradle
=> fix: pje enabler sample and password validation

certificate-analyser/src/main/java/org/zowe/apiml/Analyser.java, certificate-analyser/src/main/java/org/zowe/apiml/ApimlConf.java, certificate-analyser/src/main/java/org/zowe/apiml/Config.java, certificate-analyser/src/main/java/org/zowe/apiml/LocalHandshake.java, certificate-analyser/src/main/java/org/zowe/apiml/LocalVerifier.java, certificate-analyser/src/main/java/org/zowe/apiml/RemoteHandshake.java, certificate-analyser/src/main/java/org/zowe/apiml/SSLContextFactory.java, certificate-analyser/src/main/java/org/zowe/apiml/Stores.java, certificate-analyser/src/test/java/org/zowe/apiml/LocalHandshakeTest.java, certificate-analyser/src/test/java/org/zowe/apiml/RemoteHandshakeTest.java
=> refactor: cert analyser

gateway-service/src/main/resources/gateway-log-messages.yml
Signed-off-by: Andrew Jandacek <andrew.jandacek@broadcom.com>
General language refactor of error message descriptions
=> Gateway Log Messages language refactor

zaas-client/build.gradle
Update tomcat to resolve the known vulnerability.
=> chore: update tomcat to 9.0.54 in zaas client

apiml-utility/src/main/java/org/zowe/apiml/product/logging/ApimlDependencyLogHider.java, gateway-service/src/main/resources/application.yml
=> chore: ERROR level for jetty ssl logs

caching-service/build.gradle, gradle/versions.gradle, zaas-client/build.gradle
=> chore: Fix dependency vulnerabilities in the Caching Service

api-catalog-services/build.gradle, discoverable-client/build.gradle, discovery-service/build.gradle, gateway-service/build.gradle, gradle/publish.gradle, metrics-service/build.gradle
Publish different types of artifacts in different locations. 
Linked to #1498
=> chore: Distinguish Core and SDK publishing

metrics-service-package/src/main/resources/bin/start.sh
Feature flag for starting metrics service
=> chore: Add feature flag to metrics service

gradle/sonar.gradle, metrics-service-ui/frontend/package-lock.json, metrics-service-ui/frontend/package.json, metrics-service-ui/frontend/src/actions/user-actions.test.jsx, metrics-service-ui/frontend/src/components/Dashboard/Dashboard.test.jsx
Add tests to metric service
Linked to #1856 
=> chore: metrics tests

.github/workflows/containers.yml, config/docker/api-catalog-services.yml, config/docker/discovery-service.yml, config/docker/gateway-service.yml, integration-tests/build.gradle, integration-tests/src/test/java/org/zowe/apiml/integration/external/MetricServiceTest.java, integration-tests/src/test/java/org/zowe/apiml/util/categories/MetricsServiceTest.java
Verify that services are properly registered and displayed in metrics service
Linked to #1856 
=> chore: run metrics service as a part of IT

zaas-client/build.gradle, zaas-client/src/main/java/org/zowe/apiml/zaasclient/config/DefaultZaasClientConfiguration.java
=> chore: remove spring boot web

caching-service/README.md, mock-zosmf/README.md
Improve internal documentation around the caching service. 
Linked to #1866
=> chore: Provide basic documentation on the VSAM

metrics-service/src/main/resources/application.yml
Removes DC from Metrics Service config.
=> Chore: Remove discoverable client from MS config

api-catalog-ui/frontend/package-lock.json, api-catalog-ui/frontend/package.json, onboarding-enabler-micronaut/build.gradle
=> chore: Upgrade dependencies

.github/workflows/ci-tests.yml, .github/workflows/containers.yml, .github/workflows/create-image-without-release.yml, .github/workflows/release.yml, .github/workflows/snapshot-release.yml, .github/workflows/specific-release.yml, api-catalog-ui/build.gradle, gradle.properties, onboarding-enabler-nodejs/package.json
=> chore: set node and npm 

api-catalog-ui/frontend/src/components/Footer/Footer.jsx, api-catalog-ui/frontend/src/components/Footer/Footer.test.jsx, api-catalog-ui/frontend/src/components/Header/Header.css, api-catalog-ui/frontend/src/components/Header/Header.jsx, api-catalog-ui/frontend/src/components/Header/Header.test.jsx, api-catalog-ui/frontend/src/components/Tile/Tile.test.jsx
Migrate header and footer to Material.
Linked to #1903
=> feat: Migrate header and footer to Material UI

api-catalog-ui/frontend/src/components/DetailPage/DetailPage.css, api-catalog-ui/frontend/src/components/DetailPage/DetailPage.jsx, api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.css, api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.jsx, api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.test.jsx
Migrate detail page to Material UI.
Linked to #1891 
=> feat: Migrate detail page to Material

api-catalog-ui/frontend/src/components/Dashboard/Dashboard.css, api-catalog-ui/frontend/src/components/Dashboard/Dashboard.jsx, api-catalog-ui/frontend/src/components/Dashboard/Dashboard.test.jsx, api-catalog-ui/frontend/src/components/Login/Login.css, api-catalog-ui/frontend/src/components/Login/Login.jsx, api-catalog-ui/frontend/src/components/PageNotFound/PageNotFound.css, api-catalog-ui/frontend/src/components/PageNotFound/PageNotFound.jsx, api-catalog-ui/frontend/src/components/Search/SearchCriteria.jsx, api-catalog-ui/frontend/src/components/Search/SearchCriteria.test.jsx, api-catalog-ui/frontend/src/components/Tile/Tile.css, api-catalog-ui/frontend/src/components/Tile/Tile.jsx, api-catalog-ui/frontend/src/components/Tile/Tile.test.jsx
Migrate:
1. Dashboard
2. SearchBar
3. Tile
Linked to #1890
=> feat: Migrate dashboard to Material

.github/workflows/ci-tests.yml, .github/workflows/create-image-without-release.yml, .github/workflows/pull-request-snapshot-release.yml, .github/workflows/release.yml, .github/workflows/snapshot-release.yml, .github/workflows/specific-release.yml, gradle.properties, onboarding-enabler-nodejs/package.json
=> chore: higher timeouts

gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/AuthenticationService.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/AuthenticationServiceTest.java
Test failing randomly. This PR splits the test to verify JWTs separately.
=> chore: test one thing at a time

metrics-service/src/test/java/org/zowe/apiml/metrics/functional/MetricsFunctionalTest.java
Removed unnecessary exception signature on method.
=> Chore: Removed unnecessary exception signature

zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/ZaasClient.java, zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/TokenService.java, zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientImpl.java, zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasJwtService.java, zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientTest.java
These changes create methods that support password change via zaas client. 
Linked to #1978
=> Add Zaas methods for password change support

docs/release.md
Signed-off-by: Weiyu Jin <wjin42@uwo.ca>
made minor grammar fix in the "docs/release.md" file. 
Linked to # 1945
grammar fix
=> minor grammar fix in docs/release.md

.github/workflows/release.yml, .github/workflows/snapshot-release.yml, .github/workflows/specific-release.yml
=> Chore: Increase build time

.github/actions/setup/action.yml, .github/actions/teardown/action.yml, .github/workflows/build-conformant-images.yml, .github/workflows/ci-tests.yml, .github/workflows/containers.yml, .github/workflows/pull-request-snapshot-release.yml, .github/workflows/release.yml, .github/workflows/snapshot-release.yml, .github/workflows/specific-release.yml
Add custom `setup` and `teardown` actions that can be re-used across other workflows to reduce duplication.
Linked to #1729
=> chore: Clean up Github workflows

.github/actions/image-publish-setup/action.yml, .github/workflows/build-conformant-images.yml, .github/workflows/create-image-without-release.yml, .github/workflows/release.yml, .github/workflows/snapshot-release.yml, .github/workflows/specific-release.yml
- Add dropdown for workflow input where possible
- Require successful binary release before releasing images to reduce inconsistencies in release errors
- Require appropriate build jobs before publishing images
- Set appropriate image versions in release workflows instead of relying on downstream workflows.
Linked to #1923, #1729, #1952
=> fix: Build conformant images properly

scripts/docs/package.json, scripts/release_docs/package.json, scripts/security_sensitive/package.json
We have three utilities with incorrect license, that we need to license as EPL correclty
=> chore: Provide correct license for .json utilities

gradle/publish.gradle
Sync v2.x.x with master by not publishing micronaut enabler.
=> chore: Remove micronaut enabler from projects to publish

api-catalog-ui/frontend/src/actions/refresh-static-apis-actions.jsx, api-catalog-ui/frontend/src/actions/wizard-fetch-actions.jsx, api-catalog-ui/frontend/src/assets/css/APIMReactToastify.css, api-catalog-ui/frontend/src/components/Header/Header.css, api-catalog-ui/frontend/src/components/Header/Header.jsx, api-catalog-ui/frontend/src/components/Login/Login.jsx, api-catalog-ui/frontend/src/components/Login/Login.test.jsx, api-catalog-ui/frontend/src/components/Wizard/wizard.css
Clean up of UI bugs
Fixes #2033 
=> fix: UI bug polishing in v2

gradle/versions.gradle
Update patch versions of dependencies.
=> chore: Upgrade spring, spring-cloud-netflix, tomcat, xstream

.github/workflows/pull-request-snapshot-release.yml, discoverable-client/src/main/java/org/zowe/apiml/client/api/WebServiceController.java, gateway-service/src/main/java/org/zowe/apiml/gateway/sse/ServerSentEventProxyHandler.java, gateway-service/src/main/java/org/zowe/apiml/gateway/ws/GatewayWebSocketConfigurer.java, gateway-service/src/main/resources/application.yml, integration-tests/src/test/java/org/zowe/apiml/integration/discovery/ApiCatalogDiscoverableClientIntegrationTest.java, integration-tests/src/test/java/org/zowe/apiml/integration/proxy/ServerSentEventsProxyTest.java, integration-tests/src/test/java/org/zowe/apiml/integration/proxy/WebSocketProxyTest.java
=> fix: change ws and sse pattern 

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/instance/InstanceInitializeService.java, api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/cached/CachedProductFamilyService.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/instance/InstanceInitializeServiceTest.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/cached/CachedProductFamilyServiceTest.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/util/ServicesBuilder.java
Use Nested approach for the CachedProductFamilyServiceTest class
Remove the methods from the CachedProductFamilyService that aren't used by anyone
Linked to #1144 
=> chore: Clean and refactor tests 

gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfAuthenticationProviderTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceTest.java
=> refactor: Zosmf tests refactoring

apiml-security-common/src/main/java/org/zowe/apiml/security/common/login/ChangePasswordRequest.java, apiml-security-common/src/test/java/org/zowe/apiml/security/common/login/ChangePasswordRequestTest.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfAuthenticationProvider.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfService.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfAuthenticationProviderTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/AuthenticatedEndpointStrategyTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceTest.java
Add support to change password via zOSMF
Linked to #1418 
=> feat: Add support to change password via zOSMF

api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/ApiCatalogControllerTests.java
Refactor the Test to follow the currently used structure. 
Linked to #1144
=> chore: Refactor and clean ApiCatalogControllerTest

apiml-tomcat-common/build.gradle, apiml-tomcat-common/src/test/java/org/zowe/apiml/product/web/ApimlTomcatCustomizerTest.java, onboarding-enabler-micronaut-sample-app/build.gradle, onboarding-enabler-micronaut-sample-app/src/test/java/org/zowe/apiml/HealthControllerTest.java, onboarding-enabler-micronaut/build.gradle
=> chore: Upgrade dependency versions

.github/workflows/merge-major-version.yml, scripts/create_pull_request/index.js, scripts/create_pull_request/package-lock.json, scripts/create_pull_request/package.json, scripts/docs/package.json, scripts/release_docs/package.json, scripts/security_sensitive/package.json
When a commit is merged into the master create a Pull request to also merge it to the V2 branch. 
Linked to #2113
=> chore: Create Pull Request instead of Merge

gateway-service/src/main/java/org/zowe/apiml/gateway/filters/post/PostStoreLoadBalancerCacheFilter.java, gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/LocationFilter.java, gateway-service/src/test/java/org/zowe/apiml/gateway/filters/post/PostStoreLoadBalancerCacheFilterTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/LocationFilterTest.java
Signed-off-by: Amanda D'Errico <amanda.derrico@ibm.com>
- refactored LocationFilter and PostStoreLoadBalancerCacheFilter 
- acceptance and integration tests unaffected - update
Linked to # ([#2167](https://github.com/zowe/api-layer/issues/2167))
=> refactor: Refactored PostStoreLoadBalancerCacheFilter and LocationFilter

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/APIServiceStatusService.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/status/ApiServiceStatusServiceTest.java
Improves error handling for the API diff endpoint, making the logged exception better and adding debug logging.
Linked to #2091 
=> fix: Improve error handling for API diff endpoint

.github/actions/image-publish-setup/action.yml
=> fix: Image publish with proper input name

.github/actions/image-publish-setup/action.yml
=> fix: Typo in image setup input name

.github/workflows/ci-tests.yml, .github/workflows/containers.yml, .github/workflows/docs.yml
This mirrors https://github.com/zowe/api-layer/pull/2191 for v2.x.x
=> fix: use unique artifacts for gha

gateway-service/src/main/java/org/zowe/apiml/gateway/error/check/SecurityErrorCheck.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/saf/SafIdtAuthException.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/saf/SafIdtException.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/saf/SafRestAuthenticationService.java, gateway-service/src/main/resources/gateway-log-messages.yml, gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/SecurityErrorCheckTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/saf/SafRestAuthenticationServiceTest.java, gateway-service/src/test/resources/gateway-messages.yml
=> refactor: Improve error messages around saf idt token

README.md, mock-services/build.gradle, mock-services/src/main/java/org/zowe/apiml/zss/api/SafIdtController.java, mock-services/src/main/java/org/zowe/apiml/zss/model/Authentication.java, mock-services/src/main/java/org/zowe/apiml/zss/model/Token.java, mock-services/src/main/java/org/zowe/apiml/zss/services/SafIdtProvider.java, mock-services/src/test/java/org/zowe/apiml/zss/api/SafIdtControllerTest.java, mock-services/src/test/java/org/zowe/apiml/zss/services/SafIdtProviderTest.java
Update the way mock services handle SAF IDT token. 
Linked to #2007, #2010
=> refactor: Update the mock functionality

config/docker/api-defs/staticclient.yml, config/local/api-defs-http/staticclient.yml, config/local/api-defs/staticclient.yml, gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/saf/SafIdtProvider.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/saf/SafRestAuthenticationService.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/SafIdtScheme.java, gateway-service/src/test/java/org/zowe/apiml/acceptance/SafIdtSchemeTest.java, gateway-service/src/test/java/org/zowe/apiml/acceptance/netflix/MetadataBuilder.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/saf/SafRestAuthenticationServiceTest.java, gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/SafIdtSchemeTest.java
Further split of the SAF IDT related PR. 
Linked to #2007, #2010
=> refactor: Introduce applid to the SafIdtProvider

caching-service-package/src/main/resources/bin/start.sh, caching-service/build.gradle, caching-service/src/main/resources/application.yml, caching-service/src/main/resources/logback.xml
- Fix logback configuration
- Fix debug logging settings
- Fix start script to set log location
=> fix: caching service logging

.github/workflows/ci-tests.yml, .github/workflows/containers.yml
Allow `ci-tests.yml` to be run manually
=> chore: Allow integration tests to be run manually

.github/workflows/ci-tests.yml, .github/workflows/containers.yml
=> chore: allow tests to be run manually

.github/ISSUE_TEMPLATE/release_support.md
=> chore: update release template

api-catalog-services/build.gradle, caching-service/build.gradle, discovery-service/build.gradle, gateway-service/build.gradle, gradle/versions.gradle, metrics-service/build.gradle
There is a vulnerability within Spring that allows remote code execution in specific scenarios and setups. The vulnerable setups aren't part of the API ML. 
=> chore: Upgrade Spring to version without vulnerability

api-catalog-services/build.gradle, caching-service/build.gradle, discovery-service/build.gradle, gateway-service/build.gradle, gradle/versions.gradle, metrics-service/build.gradle
There is a vulnerability within Spring that allows remote code execution in specific scenarios and setups. The vulnerable setups aren't part of the API ML.
=> chore: Upgrade Spring to version without vulnerability 

metrics-service-ui/grafana-http-dashboard/APIML-Metrics-Service-HTTP-1648659430036.json, metrics-service-ui/grafana-http-dashboard/README
…ch includes the http dashboard json and a readme
created grafana-http-dashboard directory under metrics-service-ui which includes the http dashboard json and a readme
for importing the dashboard on other local systems
Linked to #1101
=> created grafana-http-dashboard directory under metrics-service-ui which includes the http dashboard json and a readme

.github/workflows/changelog.yml, scripts/release_docs/index.js
Current changelog action support automatic creation only for master branch. This update is using trigger branch name for checkout and PR
=> chore: more generic changlog action

.github/workflows/changelog.yml, scripts/release_docs/index.js
=> chore: more generic changlog action (#2269)

apiml-security-common/src/main/java/org/zowe/apiml/security/common/config/AuthConfigurationProperties.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/NewSecurityConfiguration.java, gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/SecurityConfiguration.java, integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/LoginTest.java, integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/LogoutTest.java, integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/QueryTest.java, integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/SafLoginTest.java, integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/SafLogoutTest.java, integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/ZosmfLoginTest.java, integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/ZosmfLogoutTest.java, integration-tests/src/test/java/org/zowe/apiml/util/SecurityUtils.java, integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReaderZaasClient.java, integration-tests/src/test/java/org/zowe/apiml/util/requests/Endpoints.java, zaas-client/src/main/java/org/zowe/apiml/zaasclient/config/ConfigProperties.java, zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientApimlBaseUrlTest.java, zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientImplHttpTests.java
This PR is a combination of:
1. Old auth related endpoints added back into the gateway service. Integration tests in /integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers were ultimately changed, along with configuration classes AuthConfigurationProperties and NewSecurityConfiguration.
2. Cherry-picking related commits from master [abdf99](https://github.com/zowe/api-layer/commit/abdf995920c5d6a4eec7f30f0170032e1074e0fe) and [046bce](https://github.com/zowe/api-layer/commit/046bce00fa3e24381fc17abddcf67f528a3b977e)
Linked to [#2242 Add v1 support for /auth related gateway endpoints back into v2.x.x branch](https://github.com/zowe/api-layer/issues/2242)
For more details about how should the code look like read the …
=> chore: Provide old path pattern support for auth related endpoints for zaas client

build.gradle, gradle/versions.gradle, metrics-service/build.gradle
=> chore: Upgrade Spring Framework

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocController.java, api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/handlers/CatalogApiDocControllerExceptionHandler.java, api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/cached/CachedApiDocService.java, api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/APIDocRetrievalService.java, api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/APIServiceStatusService.java, api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/SubstituteSwaggerGenerator.java, api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/AbstractApiDocService.java, api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3Service.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocControllerApiDocNotFoundTest.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocControllerTest.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/cached/CachedApiDocServiceTest.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/status/ApiServiceStatusServiceTest.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/status/LocalApiDocServiceTest.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/AbstractApiDocServiceTest.java, common-service-core/src/main/java/org/zowe/apiml/security/HttpsFactory.java, integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogAuthenticationTest.java, integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogEndpointIntegrationTest.java
Merge commits from master into v2.x.x
=> chore: merge master into v2

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV2Service.java, api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3Service.java, api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/OpenApiUtil.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV2ServiceTest.java, api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3ServiceTest.java, gateway-service/src/main/resources/application.yml
- Fixes swagger link in API Catalog using incorrect API version
- Add API version to Gateway
Linked to #2336, #2342
=> fix: API Catalog swagger link

gradle/versions.gradle
=> chore: Update patch version of Spring

api-catalog-services/build.gradle, caching-service/build.gradle, common-service-core/build.gradle, discovery-service/build.gradle, gateway-service/build.gradle, gradle/versions.gradle, metrics-service/build.gradle
=> chore: Upgrade logback, tomcat, netty

caching-service/src/main/java/org/zowe/apiml/caching/service/infinispan/config/InfinispanConfig.java
=> fix: Externalize index location to work with zowe env

gradle/versions.gradle
* Upgrade Netty
* Upgrade tomcat
Co-authored-by: Jakub Balhar <jakub.balhar@broadcom.net>
=> chore: Upgrade patch versions of servers

gradle/versions.gradle, metrics-service/build.gradle
=> chore: Upgrade versions
