api-catalog-ui/frontend/src/components/Header/Header.jsx
api-catalog-ui/frontend/src/components/Header/Header.test.jsx

fix for API Catalog defect: The link in the API Catalog title does not go the API Catalog title
Signed-off-by: Zikos, Christos <Christos.Zikos@ca.com>

dashboard home button fix

---

api-catalog-services/src/main/java/com/ca/mfaas/apicatalog/services/status/APIDocRetrievalService.java
api-catalog-services/src/main/java/com/ca/mfaas/apicatalog/services/status/APIServiceStatusService.java
gateway-common/src/main/java/com/ca/mfaas/product/constants/ApimConstants.java
gateway-service/src/main/java/com/ca/mfaas/gateway/filters/post/TransformApiDocEndpointsFilter.java
gateway-service/src/test/java/com/ca/mfaas/gateway/filters/post/PostFilterApiDocTransformTest.java

Avoid duplicate route prefixes in API catalog API Doc.
Main change is to ALWAYS call the pia-doc via the gateway, never directly to the serv ice.
Any api-doc which is cached by the API Catalog will set the Api-Doc-Normalised flag to true so the POST filter will now re-normalise it.
Any api-doc which does not have this flag set will go through the usual checks.
Also, remove the zuul header if it exists and do not pass it to the client
This is the story: https://rally1.rallydev.com/#/72725828452ud/detail/userstory/f32a1b01-f885-4f90-8222-061a7ec1b4a2

Call API Doc through gateway

---

docs/local-configuration.md
gateway-common/src/main/java/com/ca/mfaas/product/web/HttpConfig.java
gateway-service/src/main/java/com/ca/mfaas/gateway/ws/WebSocketProxyServerHandler.java
helloworld-spring/src/main/resources/service-configuration.yml
integration-enabler-java/build.gradle
integration-enabler-java/src/main/java/com/ca/mfaas/eurekaservice/client/config/ApiMediationServiceConfig.java
integration-enabler-java/src/main/java/com/ca/mfaas/eurekaservice/client/config/Ssl.java
integration-enabler-java/src/main/java/com/ca/mfaas/eurekaservice/client/impl/ApiMediationClientImpl.java
integration-enabler-java/src/test/java/com/ca/mfaas/eurekaservice/client/ApiMediationClientImplTest.java
integration-enabler-java/src/test/resources/https-service-configuration.yml

This pull request adds the support of HTTPS in Discovery Service into the Plain Java Enabler.
This one of the PRs that resolve #75.

Support for HTTPS in Discovery Service for Plain Java Enabler

---

scripts/apiml_cm.sh

Found and fixed a small bug in the certificate management script

Fixed a alias name when exporting a certificate

---

zowe-install/src/main/resources/scripts/setup-apiml-certificates-template.sh

Depends on https://github.com/zowe/zowe-install-packaging/pull/211

Use ZOWE_ROOT_DIR in instructions for importing z/OSMF certificates

---

config/local/discoverable-client.yml

Uses the original keystore `keystore/localhost/localhost.keystore.p12` for `discoverable-client` instead of a self-signed certificate. 
The reason is to make it easier to create new local CA and truststore for the APIML without additional steps to trust the self-signed certificate.

Use local CA signed certificate for discoverable-client on localhost

---

scripts/apiml_cm.sh

This allows a user that is not a superuser to run the `apiml_cm.sh --action trust-zosmf` without being a superuser if it has access to the the resource documented by https://github.com/zowe/docs-site/pull/316

Do not require superuser to run z/OSMF keyring import

---

api-catalog-ui/frontend/src/e2e/e2e.test.jsx
gateway-service/src/main/java/com/ca/mfaas/gateway/filters/post/TransformApiDocEndpointsFilter.java
gateway-service/src/test/java/com/ca/mfaas/gateway/filters/post/ApiDocController.java
gateway-service/src/test/java/com/ca/mfaas/gateway/filters/post/PostFilterApiDocTransformTest.java
integration-tests/src/test/java/com/ca/mfaas/apicatalog/ApiCatalogEndpointIntegrationTest.java
integration-tests/src/test/java/com/ca/mfaas/startup/impl/ApiDocFormatStartupChecker.java

Base URL and endpoints were changed to the following format:
* One prefix - should be api/v1
**Swagger example:**
host: "localhost:10010",
basePath: "/api/v1/discoverableclient",
schemes: [
"https"
]
,paths: {
/greeting: {
* Multiple prefixes
**Swagger example:**
host: "localhost:10010",
basePath: "",
schemes: [
"https"
]
,paths: {
/api/v1/discoverableclient/greeting: {

Change Base URL and endpoints in API doc

---

gateway-service/src/main/java/com/ca/mfaas/gateway/filters/post/ConvertAuthTokenInUriToCookieFilter.java
gateway-service/src/main/java/com/ca/mfaas/gateway/routing/MfaasRoutingConfig.java
gateway-service/src/test/java/com/ca/mfaas/gateway/filters/post/ConvertAuthTokenInUriToCookieFilterTest.java

This allows the correct token to be passed from a different location (e.g. zLUX iframe) to any endpoint in APIML as a cookie.
E.g.: `https://localhost:10010/ui/v1/apicatalog/?apimlAuthenticationToken=<correct_token>`
The request is then redirected to the URL without the parameter so it is not stored in the browser history.
In case of API catalog, it also redirects to the Dashboard because a request with empty path goes to log in even if the token is present.

Convert security token in query parameter to cookie

---

gateway-service/src/main/java/com/ca/mfaas/gateway/filters/pre/ZosmfFilter.java
gateway-service/src/main/java/com/ca/mfaas/gateway/routing/MfaasRoutingConfig.java
gateway-service/src/test/java/com/ca/mfaas/gateway/filters/pre/ZosmfFilterTest.java
integration-tests/README.md
security-module/src/main/java/com/ca/mfaas/security/token/TokenService.java
security-module/src/test/java/com/ca/mfaas/security/token/TokenServiceTest.java

Add z/OSMF filter to change JWT token to LTPA
Status:
* working
* **tests are in progress**
Try out:
* Obtain JWT token:
http -v -j --verify=False POST https://localhost:10010/api/v1/gateway/auth/login username=<userid> password=<password>
* Set variable:
set token=<jwt_token>
export token=<jwt_token>
* Access zOSMF - bearer:
http https://localhost:10010/api/zosmfca32/zosmf/restfiles/ds?dslevel=mfaas.* "Authorization:Bearer %token%" "X-CSRF-ZOSMF-HEADER;" --verify=no
* Access zOSMF - cookie:
http -v https://localhost:10010/api/zosmfca32/zosmf/restfiles/ds?dslevel=mfaas.* "Cookie:apimlAuthenticationToken=%token%" "X-CSRF-ZOSMF-HEADER;" --verify=no

Add z/OSMF filter to change JWT token to LTPA

---

scripts/publish_and_release.sh

This PR adds a new option `SPECIFIC_RELEASE` to the release job/script to allow specifying a custom release.

Specific release support

---

gateway-service/src/main/java/com/ca/mfaas/gateway/filters/post/TransformApiDocEndpointsFilter.java
gateway-service/src/main/resources/application.yml
gateway-service/src/test/java/com/ca/mfaas/gateway/filters/post/ApiDocController.java
gateway-service/src/test/java/com/ca/mfaas/gateway/filters/post/PostFilterApiDocTransformTest.java

Resolves bug when some services had incorrect api-doc. Difficult to recreate. 
Note: These services was using GW headers to populates some fields in swagger. These fields were not populated correctly.

Fix API doc translation

---

zowe-install/src/main/resources/scripts/setup-apiml-certificates-template.sh

It adds two variables into the template with z/OSMF keyring and user ID.
It also skips z/OSMF certificate import when certificate validation is not enabled.
Resolves https://github.com/zowe/api-layer/issues/199
Resolves https://github.com/zowe/zowe-install-packaging/issues/279

Configurable z/OSMF keyring and user in Zowe Installation

---

discovery-service/src/main/java/com/ca/mfaas/discovery/staticdef/ServiceDefinitionProcessor.java
discovery-service/src/test/java/com/ca/mfaas/discovery/staticdef/ServiceDefinitionProcessorTest.java

Related to this defect [https://rally1.rallydev.com/#/72725828452d/detail/defect/281247246244](https://rally1.rallydev.com/#/72725828452d/detail/defect/281247246244)
The defect was preventing zosmfca32 instance to be created and this was causing the authentication failure
Signed-off-by: Andrea Tabone <andrea.tabone@ca.com>

Fix instance creation defect in DS

---

api-catalog-ui/frontend/.gitignore
api-catalog-ui/frontend/src/components/Login/Login.jsx
api-catalog-ui/frontend/src/components/Login/Login.test.jsx
api-catalog-ui/frontend/src/components/Swagger/Swagger.jsx
api-catalog-ui/frontend/src/index.js

**Problem:** If you were to refresh the page while login request still wasn't resolved, the UI would still indicate a loading state and therefor prevent you from trying to sign in again.
**Cause:** Redux state was rehydrated after page refresh which includes the state of the loadingReducer.
**Solution:** Exclude loadingReducer from rehydration.

Do not restore loadingReducer state after page reload

---

README.md

The gradle wrapper is missing from the project upon cloning. The bootstrap_gradlew script needs to be run before ./gradlew build otherwise the build fails

Missing step to get the gradle wrapper

---

README.md
build.gradle
docs/idea-setup.md
docs/vscode-setup.md

Add configuration to the gradle file to generate the necessary build files to enable development in Visual Studio Code.

Add support for VSCode development

---

api-catalog-services/src/main/java/com/ca/mfaas/apicatalog/ApiCatalogApplication.java
api-catalog-services/src/main/resources/application.yml
common-service-core/src/main/java/com/ca/mfaas/security/HttpsFactory.java
discoverable-client/src/main/java/com/ca/mfaas/client/DiscoverableClientSampleApplication.java
discoverable-client/src/main/resources/application.yml
discoverable-client/src/test/resources/application.yml
discovery-service/src/main/java/com/ca/mfaas/discovery/DiscoveryServiceApplication.java
discovery-service/src/main/resources/application.yml
docs/ciphers.md
gateway-service/src/main/resources/application.yml
gateway-service/src/test/resources/application.yml
security-module/src/main/java/com/ca/mfaas/security/config/SecurityConfigurationProperties.java

- Set protocol for HTTPS clients
- Use apiml.security.ciphers as the configuration property that sets ciphers for all services
- Use server cipher ordering for all services (it used to be gateway only)

Fix for non verifying sslcontext to use specific protocol

---

gateway-common/src/main/java/com/ca/mfaas/product/routing/RoutedServices.java
gateway-common/src/main/java/com/ca/mfaas/product/routing/transform/TransformService.java
gateway-common/src/test/java/com/ca/mfaas/product/routing/RoutedServicesTest.java
gateway-common/src/test/java/com/ca/mfaas/product/routing/transform/TransformServiceTest.java

This PR cover the defects about TransformService.
1. ServiceType.All was considered as a case when client don't use ServiceType.UI,ServiceType.API or ServiceType.WS.
2. When the URL path was containing also query part (e.g. `service/login.do?action=secure`) the query part was lost during the URL transformation. Now it is kept.
3. When serviceUrl is "/", all slashes were removed from the path. Now the replacing process is skipped when serviceUrl is "/".

TransformService defects

---

api-catalog-services/src/main/resources/application.yml
discoverable-client/src/main/resources/application.yml
discovery-service/src/main/resources/application.yml
docs/ciphers.md
gateway-service/src/main/resources/application.yml

Added zD&T compatible ciphers and restricted the tls protocol being used
added `TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA` and `TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA` to our cipherset, these are compatible with browsers and also supported on zD&T.
This is good as a starting point and enables zD&T installation to be used through browser.
All scans look good with the following set on zD&T and on our system

zD&T compatible ciphers

---

README.md

Waffle.io is not used anymore. The Codecov badge used a wrong repository.

Remove Waffle badge and fix Codecov badge

---

api-catalog-ui/frontend/src/e2e/e2e.test.jsx
gateway-service/src/main/resources/application.yml

Add new e2e test to check that Gateway information are displayed correctly in the API Catalog detail page.
Signed-off-by: Andrea Tabone <andrea.tabone@ca.com>

E2E test for Gateway information

---

api-catalog-services/src/main/java/com/ca/mfaas/apicatalog/services/cached/CacheRefreshService.java
api-catalog-services/src/main/java/com/ca/mfaas/apicatalog/services/cached/CachedApiDocService.java
api-catalog-services/src/main/java/com/ca/mfaas/apicatalog/services/cached/CachedProductFamilyService.java
api-catalog-services/src/main/java/com/ca/mfaas/apicatalog/services/cached/CachedServicesService.java
api-catalog-services/src/main/java/com/ca/mfaas/apicatalog/services/initialisation/InstanceRetrievalService.java
api-catalog-services/src/test/java/com/ca/mfaas/apicatalog/services/cached/CacheRefreshServiceTest.java

Issue #283 
Hi Reviewers!
In this PR, I have implemented 2 things.
1) The first problem is service still displayed as UP even if stopped. Actually, it had been working before, it was broken after #262 implementation. I grabbed old implementation codes and I made refactoring a little bit.
2) The second part is totally new. When service is down, api-doc should be gotten from the URL otherwise it should be from the cache.
I apologize for what you see as changes. It was hard to decide a better design. I hope you will enjoy!

Service still displayed as UP and API doc available in the catalog even if stopped

---

Jenkinsfile
api-catalog-services/src/main/java/com/ca/mfaas/apicatalog/security/SecurityConfiguration.java
apiml-auth/lib/apimlAuth.js
apiml-auth/lib/tokenInjector.js
discovery-service/src/main/java/com/ca/mfaas/discovery/config/EurekaSecurityConfiguration.java
discovery-service/src/main/java/com/ca/mfaas/discovery/config/HttpsEurekaSecurityConfiguration.java
gateway-service/src/main/java/com/ca/mfaas/gateway/security/config/SecurityConfiguration.java
integration-tests/src/test/java/com/ca/mfaas/apicatalog/ApiCatalogHttpHeadersIntegrationTest.java
integration-tests/src/test/java/com/ca/mfaas/discoveryservice/EurekaInstancesIntegrationTest.java

fix for issue API Catalog cannot be loaded under zLux #312
our configuration of spring security http headers was faulty
Another change to the apiml-auth plugin for zlux to expect HTTP RC 204 from login instead of 200

fix for issue API Catalog cannot be loaded under zLux #312

---

README.md
gateway-common/src/main/resources/logback.xml
keystore/README.md
package.json

Signed-off-by: Vitek Vlcek <vitezslavvit.vlcek@ca.com>
* Adjusted logback format for API-ML based on proposal https://github.com/zowe/zlc/issues/90#issuecomment-505948963
* add new `npm run register-certificates-win` that imports `keystore/local_ca/localca.cer` into windows keystore. This depends on `sudo` installed by `chocolatey.exe install sudo`

adjust logbackformat to latest agreement

---

zowe-install/src/main/resources/scripts/setup-apiml-certificates-template.sh

added missing parameters `--zosmf-keyring **ZOSMF_KEYRING** --zosmf-userid **ZOSMF_USER**` when registering z/OSMF certs
see bugfix: https://app.slack.com/client/T1BAJVCTY/CC08782AG/thread/CC08782AG-1564487049.010900
Signed-off-by: Vitek Vlcek <vitezslavvit.vlcek@broadcom.com>

missing parms for adding zosmf cert

---

.codecov.yml

Hello,
this updates the Codecov settings to prevent SonarQube quality gate from failing when the new code coverage is lower than 80%.
The project coverage has been increased to current coverage. The coverage has improved from 55% to 70%. Thank you and keep up the good work!

Updating coverage settings to match the current state

---

apiml-common/src/main/java/com/ca/mfaas/product/logging/ApimlDependencyLogHider.java
apiml-common/src/test/java/com/ca/mfaas/product/logging/ApimlDependencyLogHiderTest.java
gateway-service/src/main/resources/application.yml

```shell
2019-10-21 11:42:39.479 <MAS2AGW1:main:67439433> MASSERV INFO  (o.a.c.h.Http11NioProtocol) Initializing ProtocolHandler ["https-jsse
-nio-0.0.0.0-10010"]
2019-10-21 11:42:50.715 <MAS2AGW1:main:67439433> MASSERV INFO  (o.a.c.h.Http11NioProtocol) Starting ProtocolHandler ["https-jsse-nio
-0.0.0.0-10010"]
2019-10-21 11:42:52.086 <MAS2AGW1:main:67439433> MASSERV INFO  (o.a.t.u.n.NioSelectorPool) Using a shared selector for servlet write
/read
```
STITUATION: From MF, when app runs
```shell
2019-10-21 11:42:53.556 <MAS2AGW1:https-jsse-nio-0.0.0.0-10010-exec-9:67439433> MASSERV WARN  (o.s.c.n.z.w.ZuulHandlerMapping) No ro
utes found from RouteLocator
```
```shell
2019-10-22 10:20:21.034 <MAS2AGW1:https-jsse-nio-0.0.0.0-10010-exec-4:17107440> MASSERV ERROR (o.a.c.c.C.[.[localhost]) …
```

Cleanup Gateway dependency logs

---

docs/local-configuration.md

* Fix startup parameter which is different in Spring 1
* Fix link
* Minor changes

Fix startup command for Sample Client

---

Jenkinsfile
build.gradle
common-service-core/src/test/java/com/ca/mfaas/tomcat/TomcatHttpsTest.java
gradle.properties

This PR contains the improvements that were discovered during working on PR-475.
We had several problems that were causing different tests to fail after different changes. These failures were not caused directly by the tests but the order of the tests.
What helped to resolve these problems that anyone can suffer from:
- Switching off parallel builds and tests
- Publishing Gradle unit tests reports to the Jenkins - they are quite friendly to use
- Making TomcatHttpsTest stabler by clearing the `javax.net.ssl` settings before the test, these can be set by other tests so the single-threaded tests and cleanup make sure that these tests will work well
Other tests that benefit from single-threaded execution are Zuul filter tests that use `RequestContext.getCurrentContext()` which can use the …

More stable builds

---

apiml-common/src/main/java/com/ca/mfaas/product/web/HttpConfig.java
common-service-core/src/main/java/com/ca/mfaas/security/HttpsFactory.java
gateway-service/src/main/java/com/ca/mfaas/gateway/config/GatewayConfig.java
gateway-service/src/main/java/com/ca/mfaas/gateway/ribbon/GatewayRibbonConfig.java
gateway-service/src/main/java/com/ca/mfaas/gateway/security/login/zosmf/ZosmfAuthenticationProvider.java

The APIML client certificates are not used when the API gateway is sending requests to z/OSMF and routing other services.
It remains to be used for inter-APIML communication.
`HttpsFactory` needs to create an empty keystore because IBMJSSE2 behavior (different from Oracle Java):
> If no KeyStore parameter is passed to the IBMJSSE2 default IbmX509 KeyManagerFactory, the factory tries to find key material by consulting the system properties
> javax.net.ssl.keyStore
> javax.net.ssl.keyStorePassword
> javax.net.ssl.keyStoreType
Source: https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.security.component.80.doc/security-component/jsse2Docs/x509keymanager.html

Client certificate is not used when it is not needed

---

gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/EncodedCharactersFilter.java
gateway-service/src/main/java/org/zowe/apiml/gateway/routing/ApimlRoutingConfig.java
gateway-service/src/main/resources/gateway-log-messages.yml
gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/EncodedCharactersFilterTest.java

Rework logs and ui messages for encoded characters

Change error message for encodedCharacterFilter

---

integration-tests/src/test/java/org/zowe/apiml/discoverableclient/MultipartPutIntegrationTest.java

Test were running only locally and there was a problem with file size when they run locally in windows.

Fixed MultipartPutIntegrationTest tests

---

CONTRIBUTING.md

The current Commit guidelines led to nonexistent URL.

Replace URL to the Commit Guideline with working one

---

api-catalog-services/build.gradle
discoverable-client/build.gradle
discovery-service/build.gradle
gateway-service/build.gradle

This way it is possible to specify the build cache and run locally
with `--build-cache` for the usage of build cache.
It is also possible to add the following to `gradle.properties` and it will apply to all builds
`org.gradle.cache=true`.

Normalize the build-info and git properties files from the bundle cache.

---

onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/config/Authentication.java
onboarding-enabler-spring/build.gradle
onboarding-enabler-spring/src/main/java/org/zowe/apiml/enable/config/EnableApiDiscoveryConfig.java
onboarding-enabler-spring/src/main/java/org/zowe/apiml/enable/register/RegisterToApiLayer.java

I fixed some problems about enabler:
1. Authentication model needs default constructor. Because spring-boot-v1 based apps fill datas from configuration different than v2.
2. Enablers use ```@InjectApimlLogger``` mechanism. But for working with auto-injection 
needs ```@EnableApimlLogger``` annotation as well. 
3. Added line, in case of building jar with spring-boot-v1 dependency.
```
jar.baseName = "${jar.baseName}-${springBootVersion}"
```
```
./gradlew onboarding-enabler-spring:build -Penabler=v1 
```
**Jar location**: build/libs/onboarding-enabler-spring-1.5.9.RELEASE-1.4.0-SNAPSHOT.jar

Enablers some fixes

---

build.gradle
gradle/versions.gradle

Signed-off-by: Ilkin Abdullayev <ilkin.abdullayev@broadcom.com>

Migration to Junit5 platform

---

discovery-service/src/main/java/org/zowe/apiml/discovery/EurekaInstanceCanceledListener.java
discovery-service/src/main/java/org/zowe/apiml/discovery/EurekaInstanceRegisteredListener.java
discovery-service/src/main/java/org/zowe/apiml/discovery/GatewayNotifier.java
discovery-service/src/main/resources/discovery-log-messages.yml
discovery-service/src/test/java/org/zowe/apiml/discovery/EurekaInstanceCanceledListenerTest.java
discovery-service/src/test/java/org/zowe/apiml/discovery/EurekaInstanceRegisteredListenerTest.java
discovery-service/src/test/java/org/zowe/apiml/discovery/GatewayNotifierTest.java

When service is registration into discovery service, discovery service notify about change all gateways. They can evict caches and speed up registry update.
This PR fix this process:
- do not notify gateway itself about its registration
- if any gateway is not available, dont distribute exception from REST (it can break whole process)
- instanceof trackstack write only message into log

handle exception on notification gateways by discovery to have safe registration process

---

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/cached/CachedProductFamilyService.java
api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/cached/CachedProductFamilyTest.java

`ERROR (o.z.a.p.r.t.TransformService) ZWEAO102E Gateway not found yet, transform service cannot perform the request` was never logged due to a problem with dependency injection of `TransformService` bean into `CacheProductFamilyService`.

Fix problem with log message not displayed

---

api-catalog-ui/frontend/package.json
api-catalog-ui/frontend/pnpm-lock.yaml
api-catalog-ui/frontend/src/components/App/App.jsx
api-catalog-ui/frontend/src/components/App/AsyncModules.jsx

To implement code splitting in react, our UI was using `react-loadable`, but since React 16+, this feature is natively implemented and it's more flexible. Code splitting allows better performance for the UI, since it loads components only on demand, and not at the beginning.
`AsyncLoginContainer`, `AsyncDashboardContainer` and `AsyncDetailPageContainer` are now using the native `React.lazy` rather than `react-loadable` for code splitting feature. They were also never used even if defined, only `AsyncAppContainer` was used. Switching it to `React.lazy` is causing some problem so it still uses `react-loadable.`

Switch to React.lazy for code splitting and use async components

---

integration-tests/src/test/java/org/zowe/apiml/gatewayservice/LogoutTest.java

Integration test LogoutTest is testing integration of REST API to z/OSMF. For this reason it is not possible to test it on localhost without dependecies and it is mark to run just on mainframe
Signed-off-by: Pavel Jareš <pavel.jares@broadcom.com>

Integration test for logout has sence only on mainframe, not on localhost

---

integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReader.java
integration-tests/src/test/resources/environment-configuration.yml

Allow overwriting of the zosmf service Id

---

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3Service.java

**HOTFIX only**
**Related problem:**
#571 
**Fixes:**
The catalog does not display OAS3 document when no tags are present. Nullpointer exception occurs instead.
**Does not fix:**
Error handling. The Catalog should not return 200 when something fails.

Fix OAS3 parser when no tags are present

---

.gitignore
config/local/api-defs/zosmf-sample.yml_
config/local/gateway-service.yml
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/ZosmfService.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceFacade.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceV1.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceV2.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/AuthenticationServiceTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceFacadeTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceV1Test.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceV2Test.java

The z/OSMF provides `/zosmf/services/authenticate` only if the JWT support is activated even on the latest version.
The code is changed to use ZosmfServiceV2 only when the endpoint is available.
Reported by @jackjia-ibm: https://openmainframeproject.slack.com/archives/CC5UUL005/p1585348336019100
Signed-off-by: Petr Plavjanik <plavjanik@gmail.com>

Use ZosmfServiceV2 only if the authentication endpoint exists

---

gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/JwtValidatorFilter.java
gateway-service/src/main/java/org/zowe/apiml/gateway/routing/ApimlRoutingConfig.java
gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/JwtValidatorFilterTest.java

resolves #583
When filter treats expired JWT token, token is removed and request send to service to allow interaction with service. PR also fix response of calls with invalid token (modified JWT)

fix JwtValidatorFilter to support expired tokens to services

---

api-catalog-ui/frontend/cypress.json

Increase default timeout value used by Cypress E2E tests to fix the problem of failing tests when MF is slow.

Increase cypress timeout

---

common-service-core/src/main/java/org/zowe/apiml/passticket/PassTicketService.java
common-service-core/src/test/java/org/zowe/apiml/passticket/PassTicketServiceTest.java
discoverable-client/src/test/java/org/zowe/apiml/client/api/PassTicketTestControllerTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketSchemeTest.java
passticket/test-programs/PtGen.java

Prevent issues when PassTicket generated for lower case user ID is not valid in mainframe services.
Signed-off-by: Petr Plavjanik <plavjanik@gmail.com>

Use uppercase parameters for PassTicket service

---

api-catalog-services/build.gradle
discoverable-client/build.gradle
discovery-service/build.gradle
gateway-service/build.gradle

These changes are aside to our build and artifacts
enable thin jar for discoverable client
change classpath from compile to runtime to fix missing dependencies

thin jar fixes

---

gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketScheme.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketSchemeTest.java

In case of call service using PassTicket authentication scheme without JWT, call should be send, but without credentials.
It is used for example in case of calling endpoints like /application/healts. Not all endpoints have to required credentials.

fix PassTicket scheme when call without JWT

---

onboarding-enabler-spring/src/main/java/org/zowe/apiml/enable/config/EnableApiDiscoveryConfig.java

I've changed the @Nullable for @Conditional, providing an option to create default bean if dependencies are not provided. @Conditional should work for V4 and V5.

Use Spring @Conditional)v4) instead of @Nullable(v5) for optional beans

---

Jenkinsfile

publish enabled on second run of jenkins, proof of publish here:
https://zowe.jfrog.io/zowe/libs-snapshot-local/org/zowe/apiml/sdk/zowe-install/1.12.0-PR-658-SNAPSHOT/

fix PR artifact publish

---

api-catalog-ui/frontend/README.md
api-catalog-ui/frontend/cypress/integration/e2e/dashboard/dashboard.test.js
api-catalog-ui/frontend/src/components/Dashboard/Dashboard.css
api-catalog-ui/frontend/src/components/Dashboard/Dashboard.jsx
api-catalog-ui/frontend/src/components/Dashboard/DashboardContainer.jsx

Implementation of the static APIs refresh functionality for the API Catalog UI #57
The user can now press a refresh button in the UI which will call the API Catalog service endpoint that will use the DS endpoint /discovery/api/v1/staticApi to refresh static APIs.
Error handling has been added. You will see a banner containing error message and related informations for the following errors:
ZWEAC706E - 503 Service Unavailable
ZWEAC707E - 500 internal error
ZWEAG708E Connection refused
ZWEAD702E Unable to process static API definition data.
In case of successful response, another "toast" popup will be displayed.
On local environment it takes few seconds (like 5 sec) to update and reflect in the UI the changes.

Add remaining react components for the refresh func

---

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIService.java
api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIServiceTest.java
gateway-service/src/main/resources/application.yml

Static refresh works with the preferIpAdress: true
Gateway allows long timeouts needed for example by /mvs/datasets

Hotfixes for the 1.12 release

---

gateway-service/build.gradle
gateway-service/src/main/java/org/zowe/apiml/gateway/GatewayApplication.java
gateway-service/src/main/java/org/zowe/apiml/gateway/cache/RetryIfExpired.java
gateway-service/src/main/java/org/zowe/apiml/gateway/cache/RetryIfExpiredAspect.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImpl.java
gateway-service/src/test/java/org/zowe/apiml/gateway/cache/RetryIfExpiredAspectTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImplTest.java

CacheEvict and Cacheable in ServiceAuthenticationServiceImpl used different key generator. For this reason expired entry cannot be evicted (different class of key).
During fixing was detected another problem, if entry is expired, it is evicted, but method return previous object from cache. It should return new value. It is fixed in this PR too.
Signed-off-by: Pavel Jareš <pavel.jares@broadcom.com>

Fix evicting of expired authentication tokens

---

apiml-common/src/main/java/org/zowe/apiml/product/web/HttpConfig.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/ApimlX509AuthenticationFilter.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/SecurityConfiguration.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/config/ApimlX509AuthenticationFilterTest.java

The problem the squad was trying to solve:
For certain endpoints the Gateway should accept only certificates issued by API Mediation Layer. The key reason  is that these endpoints leverage the Gateway certificate as an authentication method for the downstream service. This certificate has stronger privileges and as such the Gateway need to be more careful with who can use it.
This solution is risky as it removes the certificates from the chain from all subsequent processing. Despite this it seems to be the simplest solution to the problem. While exploring the topic, the API squad explored following possibilities without any results:
1) As this is more linked to the authentication, move it to the CertificateAuthenticationProvider and distinguish authentication based on the provided …

Return protection by filtering for certificate other than issued by API ML

---

discoverable-client/build.gradle
discoverable-client/src/main/java/org/zowe/apiml/client/api/ZaasClientTestController.java
discoverable-client/src/main/java/org/zowe/apiml/client/configuration/ZaasClientConfig.java
discoverable-client/src/main/java/org/zowe/apiml/client/service/ZaasClientService.java
discoverable-client/src/main/resources/application.yml
discoverable-client/src/test/java/org/zowe/apiml/client/api/ZaasClientTestControllerTest.java
integration-tests/src/test/java/org/zowe/apiml/discoverableclient/IntegratedZaasClientTest.java
zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/HttpsClientProvider.java
zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/TokenServiceHttpsJwt.java
zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientHttps.java
zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/CloseableClientProviderTest.java

Add ZAAS client do DC application, add REST endpoint to test keyring support on mainframe

Add SAF keyring support to ZAAS client 

---

integration-tests/src/test/java/org/zowe/apiml/discoverableclient/IntegratedZaasClientTest.java

Remove tests requiring the Discoverable Client from Zowe RC tests

---

.adr-dir
.codecov.yml
Jenkinsfile

The Codecov isn't used anymore to check coverage of the code for the API Layer, as such it is possible to remove the dependency.

Remove Codecov dependency

---

gateway-service/src/main/java/org/zowe/apiml/gateway/metadata/service/RibbonMetadataProcessor.java
gateway-service/src/main/resources/application.yml
gateway-service/src/test/java/org/zowe/apiml/acceptance/RetryPerServiceTest.java
gateway-service/src/test/java/org/zowe/apiml/acceptance/common/AcceptanceTestWithTwoServices.java
gateway-service/src/test/java/org/zowe/apiml/acceptance/netflix/ApplicationRegistry.java
gateway-service/src/test/resources/application.yml

Default retry policy is set to allow retry only for status codes 503, 404 and method get. Combinations of status codes 503, 404 and other methods can be enabled per service.
#701 

set ribbon retry parameter per service

---

gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/SecurityConfiguration.java
gateway-service/src/main/resources/application.yml
gateway-service/src/test/java/org/zowe/apiml/acceptance/CorsPerServiceTest.java
gateway-service/src/test/java/org/zowe/apiml/acceptance/common/AcceptanceTestWithTwoServices.java
gateway-service/src/test/resources/application.yml

zOSMF has custom handling of CORS. To make sure the CORS handling is properly delegated
to the API ML filter the CORS related headers from the response of the southbound service.
#384 

CORS headers provided by Southbound services are ignored

---

gateway-service/src/main/resources/application.yml
gateway-service/src/test/java/org/zowe/apiml/acceptance/corsTests/GatewayCorsEnabledTest.java
gateway-service/src/test/resources/application.yml

The Origin header if present can initiate CORS related behavior in the southbound
service. When API ML handles CORS it needs to remove it to prevent CORS related
issues on the southbound service.
#384 

Remove origin header from call to Southbound service if CORS is delegated to API ML

---

gradle/publish.gradle

Only the SDK related artifacts are published in the Zowe repository. As there could be extensions of the API Mediation Layer in future it is important to allow the extending parties access valid versions of the core services as well as the SDK
- [x ] New feature (non-breaking change which adds functionality)

Publish Core services as libraries to depend upon.

---

zowe-install/src/main/resources/component-scripts/configure.sh

Signed-off-by: Jordan Cain <jordan.cain1@uk.ibm.com>
Default configuration of zosmf api definition now allows encoded special characters so requests made to access datasets from UI components that do url encoding can succeed.
Fixes https://github.com/zowe/api-layer/issues/716

Created api-def for zosmf now allows encoded url characters by default

---

common-service-core/src/main/java/org/zowe/apiml/security/HttpsConfig.java

This PR continues in fixing of problem CWE ID 361 (http://cwe.mitre.org/data/definitions/316.html) particularly fixed in PR-741.
Lombok Builder generates code when a field with a password is annotated @Builder.Default which Veracode marks as vulnerable. The solution is just don't use annotation @Builder.Default if default value is the same as default value in JVM.

Fix Veracode CWE ID 316

---

discovery-service/src/main/java/org/zowe/apiml/discovery/config/HttpsWebSecurityConfig.java

Signed-off-by: Jordan Cain <jordan.cain1@uk.ibm.com>
Modify security config of discovery service so /discovery/** endpoint certificate checking is skipped unless verifySslCertificatesOfServices is set to true
Fixes https://github.com/zowe/api-layer/issues/737

Don't check validity of certs when calling discovery/** apis when verify ssl certs false

---

onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidator.java
onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidatorTest.java
onboarding-enabler-java/src/test/resources/keyring-ssl-configuration.yml
onboarding-enabler-java/src/test/resources/missing-ssl-configuration.yml

Enhancement of the spring enabler validator to list the ssl and routing props missing in the configuration. This PR also fix problem with validation of trustStorePassword and keyStorePassword, avoiding requirement for them in case of keyrings.
Fixes #745 

Configuration validator enhancement

---

build.gradle

The End2End tests often fail on the Wash system without any information about the quality of the underlying code. We got the information that under stress conditions the tests and the environment is a bit unstable and plan in future to improve as a part of the performance testing.

Remove E2E Tests run from the PR run on the Wash

---

docker/README.md
docker/development/README.md
docker/development/_run

The Docker image didn't download new dependencies when new build was running. This changed. 
Fixes #752 

Install PNPM dependencies before run

---

gateway-service/src/main/resources/application.yml
gateway-service/src/test/java/org/zowe/apiml/acceptance/ForwardedProxyHeadersTest.java
gateway-service/src/test/java/org/zowe/apiml/acceptance/common/AcceptanceTestWithBasePath.java
gateway-service/src/test/resources/application.yml

Add Proxy related headers such as X-Forwarded-Host so the southbound services can use them to construct valid links. 
Fixes #669 

Enable handling of the Proxy headers by default

---

gateway-service/src/main/java/org/zowe/apiml/gateway/routing/ApimlRouteLocator.java

Signed-off-by: Jordan Cain <jordan.cain1@uk.ibm.com>
Fixes #735 
Rather than returning null when a service has no instances, break and allow other services to to still have their routes surfaced. This means one badly configured service does not bring down the api gateway landing page.
The fix feels a bit like I'm treating the symptom rather than the cause, though I'm not sure where in the discovery service the instance creation of an invalid service is failing. 

If service has no instances don't return null routes

---

onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidator.java
onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidatorTest.java

Malformed URLs are apt to occur when the `baseUrl` or `contextPath` parameters end with a trailing `/`, and/or when `homePageRelativeUrl`, `statusPageRelativeUrl`, `healthCheckRelativeUrl`, and `contextPath` parameters don't begin with a `/`. This PR adds warnings that are logged when the `/` are not in appropriate places.
Tests were not added as there is no precedent in api-layer for using log messages as acceptance conditions, and there are no other acceptance conditions than log status.
Fixes #744 

Add warning logging for poorly formed URL config parameters

---

integration-tests/src/test/java/org/zowe/apiml/discoverableclient/IntegratedApiMediationClientTest.java

The test needs Discoverable client which isn't part of the Zowe distribution.

Mark the test as excluded from the Zowe testing.

---

api-catalog-ui/frontend/cypress/integration/e2e/detail-page/detail-page.test.js
apiml-common/src/main/java/org/zowe/apiml/product/routing/transform/TransformService.java
apiml-common/src/test/java/org/zowe/apiml/product/routing/transform/TransformServiceTest.java
common-service-core/src/main/java/org/zowe/apiml/product/routing/RoutedServices.java
gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/LocationFilter.java
gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/SlashFilter.java
gateway-service/src/main/java/org/zowe/apiml/gateway/routing/ApimlRouteLocator.java
gateway-service/src/main/java/org/zowe/apiml/gateway/routing/NewApimlRouteLocator.java
gateway-service/src/test/java/org/zowe/apiml/gateway/filters/post/PageRedirectionFilterTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/LocationFilterTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/SlashFilterTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/routing/NewApimlRouteLocatorTest.java
integration-tests/src/test/java/org/zowe/apiml/discoverableclient/DownloadApiIntegrationTest.java
integration-tests/src/test/java/org/zowe/apiml/discoverableclient/GreetingApiIntegrationTest.java
integration-tests/src/test/java/org/zowe/apiml/discoverableclient/IntegratedApiMediationClientTest.java
integration-tests/src/test/java/org/zowe/apiml/discoverableclient/IntegratedZaasClientTest.java
integration-tests/src/test/java/org/zowe/apiml/discoverableclient/MultipartPutIntegrationTest.java
integration-tests/src/test/java/org/zowe/apiml/discoverableclient/RequestInfoIntegrationTest.java
integration-tests/src/test/java/org/zowe/apiml/discoverableclient/UiIntegrationTest.java
integration-tests/src/test/java/org/zowe/apiml/gatewayservice/PageRedirectionTest.java

Allows for paths with the pattern `https://gateway.zowe.org/{serviceId}/{typeOfService}/{version}/{pathOnTheService}`, in addition to the old pattern `https://gateway.zowe.org/{typeOfService/{version}/{serviceId}`.
Fixes #688 

Implement API Path Pattern with serviceId as first element

---

integration-tests/src/test/java/org/zowe/apiml/penetration/JwtPenTest.java

Enable Passticket related pen tests. Not meant for Zowe is because it depends on the functionality of the Discoverable Client which isn't part of Zowe. 
Related to 692

Return Passticket related pen tests to the CICD pipeline

---

gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/GatewayHomepageController.java
gateway-service/src/main/java/org/zowe/apiml/gateway/health/GatewayHealthIndicator.java

as documented here: https://github.com/zowe/docs-site/pull/1371/files
`apiml.security.auth.zosmfServiceId=zosmf`
Gateway fails to start with AuthenticationServiceException.
This PR fixes so the check is performed only when started with ZOSMF auth provider

Fix handling of zosmf sid

---

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/cached/CachedApiDocService.java
api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/cached/CachedApiDocServiceTest.java

If the api doc was not retrieved for some reason and was null, a `200` HTTP status code was returned without any clear message. Instead now an API message is returned with `500` return code.
Fixes #571 

Fix problem in error handling when no api-doc is available

---

gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/AuthenticationService.java
zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/CloseableClientProvider.java
zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/HttpsClientProvider.java
zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/PassTicketServiceHttps.java
zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/TokenServiceHttpsJwt.java
zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientHttps.java
zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/CloseableClientProviderTest.java
zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientHttpsTest.java

Improve performance of query endpoint and ZAAS client
The ZAAS client had query performance measured on SDK sample including ZAAS client around 700ms. With heavy load, we measured a performance degradation up to 10x (7s per request)
After the fix, with heavy load, the requests take around 300ms and do not scale with load

Improve performance of query endpoint and ZAAS client

---

discoverable-client/src/main/java/org/zowe/apiml/client/api/ZaasClientTestController.java
discoverable-client/src/test/java/org/zowe/apiml/client/api/ZaasClientTestControllerTest.java
integration-tests/src/test/java/org/zowe/apiml/discoverableclient/IntegratedZaasClientTest.java
integration-tests/src/test/java/org/zowe/apiml/zaasclient/ZaasClientIntegrationTest.java
zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasJwtService.java
zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasJwtServiceTest.java

ZAAS client offers method logout to users. This method supports two types of JWT's "format": pure JWT, as an Authorization header value. In the case of pure JWT it set a value in the cookie, in case of authorization header set the header. Unfortunately, the setting of the cookie contains a bug and it is not working.

Fix fulfill JWT in request on ZaasClient.logout

---

gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/x509/X509AuthenticationMapper.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/x509/X509AuthenticationProvider.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/x509/X509ExternalMapper.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/TokenCreationService.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/x509/X509AuthenticationProviderTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/x509/X509ExternalMapperTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/TokenCreationServiceTest.java
gateway-service/src/test/resources/application.yml

Add JWT token to the call to the ZSS
Extract the JWT token creation without credentials to the separate class.
ZSS API providing the mapping functionality for certificate is secured by JWT token in the same way as Single Sign On. 
Linked to #827 
- [] Any dependent changes have been merged and published in downstream modules

Call ZSS with valid JWT token

---

gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/JWTLogoutHandler.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/AuthenticationService.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/config/JWTLogoutHandlerTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/AuthenticationServiceTest.java
integration-tests/src/test/java/org/zowe/apiml/discoverableclient/IntegratedZaasClientTest.java
integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/DummyLogoutTest.java
integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/LogoutTest.java
integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/SafLogoutTest.java
integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/ZosmfAuthenticationLoginIntegrationTest.java
integration-tests/src/test/java/org/zowe/apiml/gatewayservice/authentication/ZosmfLogoutTest.java
zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasJwtService.java
zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientImplHttpsTests.java

This introduces the two following behaviours for the Gateway logout endpoint:
- When a previously invalidated token is attempted to be invalidated (logged out) again, the Gateway now returns a 401 with explanation, rather than a 204 response.
- When a token is valid but an unknown error happens during logout, the Gateway now returns a generic 500 internal server error.
Fixes #831 

Improve Gateway logout endpoint error handling

---

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/SubstituteSwaggerGenerator.java
api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/AbstractApiDocService.java
api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV2Service.java
api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3Service.java
api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/OpenApiUtil.java
api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/status/LocalApiDocServiceTest.java
api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/SubstituteSwaggerGeneratorTest.java
api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/AbstractApiDocServiceTest.java
api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV2ServiceTest.java
api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3ServiceTest.java
api-catalog-ui/frontend/cypress/integration/e2e/detail-page/detail-page.test.js
gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/GatewayHomepageController.java
gateway-service/src/test/java/org/zowe/apiml/gateway/controllers/GatewayHomepageControllerTest.java
integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogEndpointIntegrationTest.java

Sets all base paths used in the API catalog to be of the format `/{serviceId}/{type}/{version}` rather than the old format of `/{type}/{version}/{serviceId}`.
Fixes #853 

Consistent path pattern in API Catalog

---

gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/x509/model/CertMapperResponse.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/x509/X509ExternalMapperTest.java

Change in the ZSS API. 
Linked to 827

Use the names actually provided by ZSS

---

zowe-install/src/main/resources/component-scripts/start.sh

Add mapping of the system property `spring.profiles.include` from the `instance.env` to the start.sh script
Fixes #901 
Depends on https://github.com/zowe/zowe-install-packaging/pull/1774 (zowe-install-pkg)
Depends on https://github.com/zowe/docs-site/pull/1481 (Zowe docs)

Add system property for spring profiles

---

README.md

Update the documentation to replace the dummy related info to mock zosmf related info.

Update the default username and password in the documentation 

---

apiml-security-common/src/main/java/org/zowe/apiml/security/common/auth/AuthenticationScheme.java
apiml-security-common/src/main/java/org/zowe/apiml/security/common/auth/AuthenticationSchemes.java
apiml-security-common/src/test/java/org/zowe/apiml/security/common/auth/AuthenticationSchemesTest.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImpl.java

Fixes issue around the thread-unsafe access to the map with the mapping of the authentication scheme.

Remove risk around the concurrent access to Map created after constructor

---

api-catalog-services/build.gradle
apiml-common/src/main/java/org/zowe/apiml/product/web/HttpConfig.java
discovery-service/build.gradle
gateway-service/build.gradle
gateway-service/src/main/java/org/zowe/apiml/gateway/ws/ServletSslContextFactoryProvider.java
gateway-service/src/main/java/org/zowe/apiml/gateway/ws/SslContextFactoryProvider.java
gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketProxyServerHandler.java
gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketRoutedSession.java
gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketRoutedSessionFactory.java
gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketRoutedSessionFactoryImpl.java
gradle/versions.gradle
integration-tests/src/test/java/org/zowe/apiml/ws/WebSocketProxyTest.java

Upgrade dependencies that were identified as security risks to the most recent version.
* snakeyaml 1.23 -> 1.27
* commons-validator 1.6 -> 1.7
* jetty:websocket-client and jetty-util 9.4.11.v20180605 -> 9.4.35v20201120
Due to the jetty upgrade, jetty:websocket-common was added as an explicit dependency and where `SslContextFactory` was used was refactored to use `SslContextFactory.Server` as required by jetty.
Fixes #933 

Upgrade dependencies

---

apiml-common/src/main/java/org/zowe/apiml/product/web/HttpConfig.java

TLS v1.0, v1.1 and SSL v3 are no longer supported by default in current version of jetty. This will re-enable the ciphers.

re-enable ciphers

---

gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/AuthController.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/AuthenticationService.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/AuthenticationServiceTest.java
integration-tests/src/test/java/org/zowe/apiml/discoverableclient/IntegratedZaasClientTest.java

Logout endpoint behaves in different way when running in HA mode. This fix should consolidate the behaviour.

Invalidate JWT with multiple GW instances

---

integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogSecurityIntegrationTest.java

The test is flaky and is failing due to errors in the zOSMF behavior and on top of that there is another one, that tests the same behavior. 
@Test
@TestsNotMeantForZowe
void loginToGatewayAndAccessProtectedEndpointWithCookie() {
String token = SecurityUtils.gatewayToken(USERNAME, PASSWORD);
given()
.cookie(COOKIE, token)
.when()
.get(String.format("%s://%s:%d%s", SCHEME, HOST, PORT, PROTECTED_ENDPOINT))
.then()
.statusCode(is(SC_OK));
}

Remove duplicate test

---

gateway-service/build.gradle

The WebSocket library was packaged in the old version. This is the needed update. 

Update the commons library for Gateway

---

caching-service/src/main/java/org/zowe/apiml/caching/api/CachingController.java
caching-service/src/main/java/org/zowe/apiml/caching/service/Messages.java
caching-service/src/main/java/org/zowe/apiml/caching/service/StorageException.java
caching-service/src/main/java/org/zowe/apiml/caching/service/inmemory/InMemoryStorage.java
caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/VsamStorage.java
caching-service/src/test/java/org/zowe/apiml/caching/api/CachingControllerTest.java
caching-service/src/test/java/org/zowe/apiml/caching/service/inmemory/InMemoryStorageTest.java
gateway-service/build.gradle

In order to introduce the eviction mechanism later on, there was need to propagate the information about problems encountered within the storage. 
The exception was added and the refactoring is part of this effort to propagate other states from the storage via the exception. 
The changes in the Controller were done to prevent another 4 catch clauses duplicating the behavior and to limit duplicity that was already present. I am not hundred percent persuaded about the move to lambdas so if you feel it's making the solution more confusing, I will adapt the Controller to handle the Exception properly in another way. 
Part of #998

Introduce StorageException to transfer information from Storage

---

integration-tests/README.md
integration-tests/src/test/resources/environment-configuration.yml

This PR makes the `runLocalIntegrationTests` gradle task pass again

Fix running local integration tests for zOSMF related tests

---

caching-service/src/main/java/org/zowe/apiml/caching/service/inmemory/config/InMemoryConfiguration.java

Fixing configuration when VSAM is used. 
Linked to #998

InMemory is used only when no other is configured.

---

caching-service/src/main/java/org/zowe/apiml/caching/service/Messages.java
caching-service/src/main/java/org/zowe/apiml/caching/service/inmemory/InMemoryStorage.java
caching-service/src/main/java/org/zowe/apiml/caching/service/inmemory/config/InMemoryConfig.java
caching-service/src/main/java/org/zowe/apiml/caching/service/inmemory/config/InMemoryConfiguration.java
caching-service/src/main/resources/caching-log-messages.yml
caching-service/src/test/java/org/zowe/apiml/caching/service/inmemory/InMemoryStorageTest.java
integration-tests/src/test/java/org/zowe/apiml/cachingservice/RejectEvictionTest.java

As a part of the work on the Eviction strategies this PR implements the size for the InMemory cache and an Integration test which works for the InMemory and should work for other storages as well. 
Linked to #998

Support the Size limitation in the InMemory cache. 

---

apiml-common/src/main/java/org/zowe/apiml/product/web/HttpConfig.java
common-service-core/src/main/java/org/zowe/apiml/security/ApimlPoolingHttpClientConnectionManager.java
common-service-core/src/main/java/org/zowe/apiml/security/HttpsConfig.java
common-service-core/src/main/java/org/zowe/apiml/security/HttpsFactory.java
common-service-core/src/test/java/org/zowe/apiml/security/ApimlPoolingHttpClientConnectionManagerTest.java

SSL context is not allowed to be shared if it is not user specific. This will lead to opening new connection for every request, storing the connection as available but never reuse it.
from documentation: "HttpClient relies on UserTokenHandler interface to determine if the given execution context is user specific or not. The token object returned by this handler is expected to uniquely identify the current user if the context is user specific or to be null if the context does not contain any resources or details specific to the current user. The user token will be used to ensure that user specific resources will not be shared with or reused by other users. " 
Fixes #1009 
For more details about how …

associate https connections with user token, configure timeouts

---

apiml-utility/src/test/java/org/zowe/apiml/product/monitoring/LatencyUtilsConfigInitializerTest.java
gradle/versions.gradle
integration-tests/build.gradle
integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogEndpointIntegrationTest.java
integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogHttpHeadersIntegrationTest.java
integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogLoginIntegrationTest.java
integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogSecurityIntegrationTest.java
integration-tests/src/test/java/org/zowe/apiml/discoverableclient/GreetingApiIntegrationTest.java
integration-tests/src/test/java/org/zowe/apiml/discoverableclient/GreetingV2ApiIntegrationTest.java
integration-tests/src/test/java/org/zowe/apiml/discoverableclient/UiIntegrationTest.java
integration-tests/src/test/java/org/zowe/apiml/discoveryservice/EurekaInstancesIntegrationTest.java
integration-tests/src/test/java/org/zowe/apiml/discoveryservice/staticdef/StaticClientRoutingEndpointsTest.java
integration-tests/src/test/java/org/zowe/apiml/gatewayservice/AuthenticationOnDeploymentTest.java
integration-tests/src/test/java/org/zowe/apiml/gatewayservice/GatewayConcurrentRequestsTest.java
integration-tests/src/test/java/org/zowe/apiml/gatewayservice/GatewaySecurityTest.java
integration-tests/src/test/java/org/zowe/apiml/gatewayservice/GatewayTimeoutTest.java
integration-tests/src/test/java/org/zowe/apiml/gatewayservice/PassTicketTest.java
integration-tests/src/test/java/org/zowe/apiml/gatewayservice/PublicKeyIntegrationTest.java
integration-tests/src/test/java/org/zowe/apiml/startup/ApiMediationLayerStartTest.java
integration-tests/src/test/java/org/zowe/apiml/util/http/HttpRequestUtils.java
integration-tests/src/test/java/org/zowe/apiml/util/service/RequestVerifier.java
integration-tests/src/test/java/org/zowe/apiml/util/service/VirtualService.java
integration-tests/src/test/java/org/zowe/apiml/ws/WebSocketProxyTest.java
onboarding-enabler-java-sample-app/src/test/java/org/zowe/apiml/hwsjersey/ServletContextListenerTest.java
onboarding-enabler-java-sample-app/src/test/java/org/zowe/apiml/hwsjersey/greeting/GreetingControllerTest.java
onboarding-enabler-java-sample-app/src/test/java/org/zowe/apiml/hwsjersey/health/HealthControllerTest.java
onboarding-enabler-spring/build.gradle

Removes remaining references to JUnit4, except in modules that have blocking dependencies.
Fixes #1105 
- [n/a] I have performed a self-review of my own code

Upgrade remaining unit tests to JUnit 5

---

Jenkinsfile

Recent changes in port allocation make the port conflict with the running instance from build step. It is not needed to build again on publish as build has already happened in build step.

Disable repeated test on publish artifacts

---

gateway-package/src/main/resources/bin/start.sh

Propagate the possibility to set up the API Catalog to the startup script with the current state as default. 
Related to #727

Configure another service instead of Catalog

---

.github/workflows/ci-tests-without-jwt-with-authenticate.yml
apiml-security-common/src/main/java/org/zowe/apiml/security/common/config/AuthConfigurationProperties.java
gateway-package/src/main/resources/bin/start.sh
gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/ComponentsConfiguration.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/Providers.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/SaveZosmfPublicKeyConsoleApplication.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfAuthenticationProvider.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfConfiguration.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfJwkToPublicKey.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/AbstractZosmfService.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfService.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/ProvidersTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfAuthenticationProviderTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/login/zosmf/ZosmfJwkToPublicKeyTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceTest.java
mock-zosmf/src/main/java/org/zowe/apiml/client/api/AuthenticationController.java
mock-zosmf/src/main/java/org/zowe/apiml/client/api/JwtController.java
mock-zosmf/src/main/java/org/zowe/apiml/client/services/apars/AuthenticateApar.java
mock-zosmf/src/main/java/org/zowe/apiml/client/services/apars/FunctionalApar.java
mock-zosmf/src/main/java/org/zowe/apiml/client/services/apars/JwtKeys.java
mock-zosmf/src/main/java/org/zowe/apiml/client/services/apars/PH12143.java
mock-zosmf/src/main/java/org/zowe/apiml/client/services/versions/AvailableApars.java
mock-zosmf/src/test/java/org/zowe/apiml/client/api/JwtControllerTest.java
mock-zosmf/src/test/java/org/zowe/apiml/client/services/apars/AuthenticationAparTest.java
mock-zosmf/src/test/java/org/zowe/apiml/client/services/apars/JwtKeysTest.java
mock-zosmf/src/test/java/org/zowe/apiml/client/services/apars/PH12143Test.java
mock-zosmf/src/test/java/org/zowe/apiml/client/services/apars/PHBaseTest.java
mock-zosmf/src/test/java/org/zowe/apiml/client/services/versions/AvailableAparsTest.java

Allow the user to force the authentication token to be used. LTPA, JWT
Improve the default auto configuration to handle the case when the zOSMF has /zosmf/services/authenticate endpoint but doesn't support JWT.
Linked to #1239

fix(authentication): Support specific zOSMF version, allow override

---

.github/workflows/ci-internal-tests.yml
.github/workflows/ci-tests-with-rsu2012.yml
.github/workflows/ci-tests-without-jwt-with-authenticate.yml
.github/workflows/ci-tests-without-jwt.yml
.github/workflows/ci-tests.yml
integration-tests/src/test/java/org/zowe/apiml/apicatalog/ApiCatalogEndpointIntegrationTest.java

chore: Always store test results and logs

---

gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/VersionController.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/SecurityConfiguration.java

The /api/v1/gateway or /gateway/api/v1 are an issue as it may route the request to another Gateway, 

fix: Move version related endpoint to /application/version

---

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/ApiCatalogController.java
api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocController.java
apiml-security-common/src/main/java/org/zowe/apiml/security/common/error/AbstractExceptionHandler.java
apiml-security-common/src/test/java/org/zowe/apiml/security/common/auth/SafMethodSecurityExpressionControllerTest.java
apiml-security-common/src/test/java/org/zowe/apiml/security/common/error/AuthExceptionHandlerTest.java
caching-service/src/main/java/org/zowe/apiml/caching/api/CachingController.java
discoverable-client/src/main/java/org/zowe/apiml/client/api/PageRedirectionController.java
discoverable-client/src/main/java/org/zowe/apiml/client/api/PetController.java
discoverable-client/src/main/java/org/zowe/apiml/client/api/RequestInfoController.java
gateway-service/src/main/java/org/zowe/apiml/gateway/apidoc/reader/ApiDocController.java
gateway-service/src/main/java/org/zowe/apiml/gateway/controllers/VersionController.java
gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/TomcatFilter.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/query/SuccessfulQueryHandler.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/ticket/SuccessfulTicketHandler.java
gateway-service/src/main/java/org/zowe/apiml/gateway/services/ServicesInfoController.java
gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/TomcatFilterTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/query/SuccessfulQueryHandlerTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/ticket/SuccessfulTicketHandlerTest.java
integration-tests/src/test/java/org/zowe/apiml/gatewayservice/ZosmfAuthenticationTest.java
integration-tests/src/test/java/org/zowe/apiml/util/service/VirtualService.java
onboarding-enabler-spring-v1-sample-app/src/test/java/org/zowe/apiml/sample/enable/v1/controller/SampleControllerUnitTests.java

Replace deprecated constant MediaType.APPLICATION_JSON_UTF8_VALUE with MediaType.APPLICATION_JSON_VALUE

Remove deprecated use of MediaType.APPLICATION_JSON_UTF8_VALUE

---

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/APIDocRetrievalService.java
api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/APIServiceStatusService.java
api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/status/LocalApiDocServiceTest.java
discoverable-client/src/main/java/org/zowe/apiml/client/api/PetControllerExceptionHandler.java
discoverable-client/src/test/java/org/zowe/apiml/client/api/PageRedirectionControllerTest.java
discoverable-client/src/test/java/org/zowe/apiml/client/api/PetControllerPostPetTest.java
discoverable-client/src/test/java/org/zowe/apiml/client/api/PetControllerPutTest.java
discoverable-client/src/test/java/org/zowe/apiml/client/api/ZaasClientTestControllerTest.java
gateway-service/src/main/java/org/zowe/apiml/gateway/error/check/RibbonRetryErrorCheck.java
gateway-service/src/main/java/org/zowe/apiml/gateway/error/check/SecurityErrorCheck.java
gateway-service/src/main/java/org/zowe/apiml/gateway/error/check/ServiceErrorCheck.java
security-service-client-spring/src/main/java/org/zowe/apiml/security/client/service/GatewaySecurityService.java
security-service-client-spring/src/test/java/org/zowe/apiml/security/client/service/GatewaySecurityServiceTest.java

Replaces the use of the deprecated constant MediaType.APPLICATION_JSON_UTF8 with MediaType.APPLICATION_JSON.

Remove deprecated use of MediaType.APPLICATION_JSON_UTF8

---

api-catalog-services/src/main/resources/application.yml

The API Catalog wasn't using the apiml.service.id at all, unlike other services. 
Linked to #1426

Use the apiml.service.id the same way as in other services.

---

config/local/gateway-service.yml
gateway-service/src/main/java/org/zowe/apiml/gateway/config/GatewayConfig.java
gateway-service/src/main/resources/application.yml
gateway-service/src/test/resources/application-test.yml
gateway-service/src/test/resources/application.yml

Behaving like so now:
```
attls, -Dserver.internal.enabled=false
Eureka Configuration Bean: EurekaInstanceConfigBean{hostInfo=org.springframework.cloud.commons.util.InetUtils$HostInfo@45d1162f, inetUtils=org.springframework.cloud.commons.util.InetUtils@40c0bf62, appname='unknown', appGroupName='null', instanceEnabledOnit=false, nonSecurePort=10010, securePort=0, nonSecurePortEnabled=true, securePortEnabled=false, leaseRenewalIntervalInSeconds=30, leaseExpirationDurationInSeconds=90, virtualHostName='unknown', instanceId='localhost:gateway:10010', secureVirtualHostName='unknown', aSGName='null', metadataMap={management.port=10010}, dataCenterInfo=com.netflix.appinfo.MyDataCenterInfo@1b72ffb1, ipAddress='127.0.0.1', statusPageUrlPath='/actuator/info', …
```

fix: Gateway SID and Ports incorrect for TLS/ATTLS and Internal port

---

discoverable-client/build.gradle
discoverable-client/src/main/java/org/zowe/apiml/client/configuration/SecurityConfiguration.java
gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketRoutedSession.java
integration-tests/src/test/java/org/zowe/apiml/integration/proxy/WebSocketProxyTest.java

feat: websocket authentication support

---

caching-service/src/main/java/org/zowe/apiml/caching/service/redis/RedisOperator.java
caching-service/src/test/java/org/zowe/apiml/caching/service/redis/RedisOperatorTest.java

Conditionally close redis connections instead of closing every time the caching service is shut down.
Linked to # 1465

fix: Conditionally close redis connections

---

.github/workflows/ci-tests.yml

fixes #1527
I have this in two branches and the keys are different between them. They should be different commit to commit as well as `github.sha` represents the commit hash.

fix: key cache on commit hash

---

zaas-client/src/main/java/org/zowe/apiml/zaasclient/config/ConfigProperties.java
zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientImpl.java
zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasHttpsClientProvider.java
zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientImplHttpTests.java
zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientTest.java
zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasHttpsClientProviderTests.java

Signed-off-by: Pavel Jareš <pavel.jares@broadcom.com>
This PR changes the setting of HTTP clients in ZAAS client. It uses now two different clients: 
- for passticket endpoint '/ticket' with signing by a certificate
- for the rest of the endpoints (login, query, logout) without keyring in configuration
Change also required to move verification about settings of keyring to another class. Therefore few tests should be moved and fixed.
It will be great to put In the right documentation warning about using ZAAS client (but I am not sure where). ZAAS client before this PR should be used only against Gateway with disabled client certificates and each application using ZAAS client should be upgraded as soon as possible to avoid this issue.
Linked to #1513  (issue)
Please delete options that are …

Fix wrong using of certificates in ZAAS client

---

metrics-service-ui/frontend/.eslintrc

After clean clone of api-layer I was not able to build it on Windows machine. Possibly wrong setup of git client, but the fix proposed here solved the issue regardless of the git client config.
Added single line for auto handling of the OndOfLine
- [X ] (fix) Bug fix (non-breaking change which fixes an issue)

Fix for failing build due to Linux/IOS/Windows endofline differnces.

---

integration-tests/src/test/java/org/zowe/apiml/functional/discovery/EurekaInstancesIntegrationTest.java

The tests are randomly failing. This uncovered behavior that is captured in #1548 and #1549 until these are fixed the tests are disabled.

chore: Disable flaky tests. Related issues are in repo

---

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/discovery/DiscoveryConfigProperties.java
api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/instance/InstanceRetrievalService.java
api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIService.java
api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/instance/InstanceRetrievalServiceTest.java
api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/staticapi/StaticAPIServiceTest.java

Fixes bug where multiple discovery service instances broke the static API refresh functionality in the API Catalog.
Linked to #1512 

fix: Handle multiple discovery service instances in static refresh

---

security-service-client-spring/src/main/java/org/zowe/apiml/security/client/handler/RestResponseHandler.java
security-service-client-spring/src/test/java/org/zowe/apiml/security/client/handler/RestResponseHandlerTest.java

If there is a misconfiguration for the authentication service, when trying to login the API Catalog logs this message:
```
2021-07-02 14:55:22.516 <ZWEAAC1:https-jsse-nio-127.0.0.1-10014-exec-4:65854> at670475 ERROR (o.a.c.c.C.[.[.[.[dispatcherServlet]) Servlet.service() for servlet [dispatcherServlet] in context with path [/apicatalog] threw exception
org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 : [{"messages":[{"messageType":"ERROR","messageNumber":"ZWEAG708E","messageContent":"The request to the URL '/gateway/api/v1/auth/login' failed after retrying on all known service instances. Caused by: java.net.ConnectException: Connection refused (Connection …
```

fix: Fix login error handling when auth service is not available

---

gradle/publish.gradle
onboarding-enabler-spring/build.gradle

Removes publishing v1 and v2 of `onboarding-spring-enabler` and stops publishing the spring enabler with the spring boot version in the name. Now it will follow the same publishing format as all other projects where there will be `onboarding-enabler-spring/${zoweApimlVersion}`. In addition to consistency and reduced complexity of publishing two equivalent versions, this will make documenting use of the enabler much easier, as the artifact name will be consistent instead of changing each time the Zowe APIML spring boot version changes.
Docs PR to document this is to come.
Linked to #1574 

fix: Publish spring onboarding enabler in format consistent with other projects

---

api-catalog-services/src/main/resources/application.yml
discovery-service/src/main/java/org/zowe/apiml/discovery/config/HttpsWebSecurityConfig.java
discovery-service/src/main/resources/application.yml
integration-tests/src/test/java/org/zowe/apiml/functional/discovery/EurekaInstancesIntegrationTest.java

unprotects health and info endpoints
Fixes https://github.com/zowe/api-layer/issues/1609

fix: Discovery health and info endpoints auth and enablement

---

gateway-service/src/main/java/org/zowe/apiml/gateway/cache/CachingServiceClient.java
gateway-service/src/main/java/org/zowe/apiml/gateway/cache/CachingServiceClientException.java
gateway-service/src/main/java/org/zowe/apiml/gateway/cache/LoadBalancerCache.java
gateway-service/src/main/java/org/zowe/apiml/gateway/filters/post/PostStoreLoadBalancerCacheFilter.java
gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/loadbalancer/predicate/AuthenticationBasedPredicate.java
gateway-service/src/test/java/org/zowe/apiml/gateway/cache/CachingServiceClientTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/cache/LoadBalancerCacheTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/loadbalancer/predicate/AuthenticationBasedPredicateTest.java

Fix several bugs and some refactors to make the remote cache behave consistently
Description of the bugs
- When cache record exists locally but not on remote, the check in post-store filter (whether the instance is already cached) returned true (local) cache and remote cache was never updated.
- Another one is when cache is stored locally, and then retrieved from remote, then inconsistent behavior happens when remote disappears or fails. The stores to local never happens.
- Another bug is that cache record did never get updated thanks to 409 Conflict from caching service. This led to cache record never updating and expiring after 8 hours since "first" usage, and not the "last" usage.
Linked to #1412

fix: Load balancer remote cache bugs

---

gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketClientFactory.java
gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketProxyServerHandler.java
gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketRoutedSession.java
gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketRoutedSessionFactory.java
gateway-service/src/main/java/org/zowe/apiml/gateway/ws/WebSocketRoutedSessionFactoryImpl.java
gateway-service/src/test/java/org/zowe/apiml/gateway/ws/WebSocketProxyServerHandlerTest.java

Jetty client was originally incorrectly created on every websocket session creation. The websocket session itself was being closed but it did not close the underlying client, causing memory leak and additional overhead in creating the client instance.
Now the change creates just one shared client, which is economic. Also the websocket session creation is much faster now, resulting in increased performance. The thread count and memory footprint over some amount of time is constant.
Profiling before the fixes:
Profiling result after the fixes:
Linked to #1622 

fix: Reuse Jetty client to prevent out of memory

---

apiml-common/src/main/java/org/zowe/apiml/product/web/HttpConfig.java

There are log messages in Gateway log, showing that weak cipher suites are configured on websocket client. These are not configured suites. Therefore this pull request aims to configure them as per gateway's confguration.
```
2021-08-03 09:06:49.923 <ZWEAGW1:main:3380> dj657854 WARN  (org.eclipse.jetty.util.ssl.SslContextFactory.config) Weak cipher suite TLS_RSA_WITH_AES_256_CBC_SHA256 enabled for Server@7145dad9[provider=null,keyStore=file:///C:/workspace/prod/api-layer/keystore/localhost/localhost.keystore.p12,trustStore=file:///C:/workspace/prod/api-layer/keystore/localhost/localhost.truststore.p12]
2021-08-03 09:06:49.923 <ZWEAGW1:main:3380> dj657854 WARN  (org.eclipse.jetty.util.ssl.SslContextFactory.config) Weak cipher suite …
```

fix: configure WebSocket cipher suites

---

gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/saf/SafIdtProvider.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/saf/SafProviderBeansConfig.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/saf/SafRestAuthenticationService.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/SafIdtScheme.java
gateway-service/src/main/resources/application.yml
gateway-service/src/test/java/org/zowe/apiml/acceptance/DeterministicUserBasedRoutingTest.java
gateway-service/src/test/java/org/zowe/apiml/acceptance/SafIdtSchemeTest.java
gateway-service/src/test/java/org/zowe/apiml/acceptance/netflix/ApplicationRegistry.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/saf/SafRestAuthenticationServiceTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/SafIdtSchemeTest.java
gateway-service/src/test/resources/application-test.yml
gateway-service/src/test/resources/application.yml
mock-zosmf/README.md
mock-zosmf/src/main/java/org/zowe/apiml/MockServicesApplication.java
mock-zosmf/src/main/java/org/zowe/apiml/zss/api/SafIdtController.java
mock-zosmf/src/main/java/org/zowe/apiml/zss/model/Authentication.java
mock-zosmf/src/main/java/org/zowe/apiml/zss/model/Token.java
mock-zosmf/src/main/java/org/zowe/apiml/zss/services/SafIdtProvider.java
mock-zosmf/src/test/java/org/zowe/apiml/zss/api/SafIdtControllerTest.java
mock-zosmf/src/test/java/org/zowe/apiml/zss/services/SafIdtProviderTest.java

It is possible to create REST API to generate and verify SAF IDT token and as long as it adheres to the specification, it will be usable by the REST provider. 
Linked to #1629 

feat: Introduce rest provider for SAF tokens

---

api-catalog-package/build.gradle
apiml-common-lib-package/build.gradle
caching-service-package/build.gradle
discovery-package/build.gradle
gateway-package/build.gradle
metrics-service-package/build.gradle

Adds an explicit null check for `pullRequest` property in package builds, so `-null` is not added in place of the pull request number in the zip file.

fix: Add remove null from packaged service files

---

apiml-security-common/src/main/java/org/zowe/apiml/security/common/config/AuthConfigurationProperties.java
config/docker/gateway-service.yml
gateway-service/src/main/java/org/zowe/apiml/gateway/security/config/NewSecurityConfiguration.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/refresh/SuccessfulRefreshHandler.java
gateway-service/src/main/resources/application.yml
gateway-service/src/main/resources/gateway-api-doc.json
gateway-service/src/test/java/org/zowe/apiml/gateway/security/refresh/SuccessfulRefreshHandlerTest.java
gateway-service/src/test/resources/application-test.yml
gateway-service/src/test/resources/application.yml
integration-tests/src/test/java/org/zowe/apiml/integration/authentication/providers/RefreshTest.java

Adds and documents a `auth/refresh` endpoint for prolonging valid JWT token.
Linked to #1719 

feat: Refresh endpoint for prolonging valid JWT token

---

apiml-utility/src/main/java/org/zowe/apiml/product/logging/ApimlDependencyLogHider.java

Hide log messages that provide no value to the customer.
Linked to #1663

fix: hide log messages with no value

---

api-catalog-package/src/main/resources/bin/start.sh
api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/staticapi/StaticDefinitionGenerator.java
integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogEndpointIntegrationTest.java

Integration test with cleanup
Do not truncate serialized data
force unix line separators in serialized data
Linked to #1725

fix: static definition generation tweaks

---

zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasHttpsClientProvider.java
zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasHttpsClientProviderTests.java

ZAAS HTTPS client is sending also a certificate during authentication. It is expected to send only credentials without certificates. This can lead to incorrect behavior in Zowe 1.23 and lower.
https://github.com/zowe/api-layer/issues/1513
Note: My tests are not really good. Feel free to suggest how to test it in a better way.

Fix Zaas client to not send a certificate during authentication 

---

gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/AuthenticationServiceTest.java

The `AuthenticationServiceTest.testCreateJwtTokenUserExpire` is pretty flaky, due to a wrong comparison of the two tokens expiration time values which takes in consideration also the current time in the calculation.
Because of that, the test is randomly failing based on its execution speed.
Example:
```
org.opentest4j.AssertionFailedError: 
Expected :1631266367000
Actual   :1631266368000
```
Linked to #1745 

fix: Fix flaky unit test

---

gateway-service/src/main/resources/application.yml

Fixes Zuul concurrency configuration when semaphore strategy is used. Unifies it with the `APIML_MAX_TOTAL_CONNECTIONS` property.
Linked to #1779 

Fix: Zuul semaphore concurrency configuration

---

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/security/SecurityConfiguration.java
integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogAuthenticationTest.java

Adds ability to authenticate via certificates for the static refresh endpoint in the API Catalog.
Linked to #1767

feat: Certificate authentication for static refresh endpoint

---

.github/workflows/release.yml
.github/workflows/snapshot-release.yml
.github/workflows/specific-release.yml

Fix `relase` typo in workflow names

chore: Github actions workflow name typo

---

.github/workflows/containers.yml
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfService.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfServiceTest.java
mock-zosmf/src/main/java/org/zowe/apiml/client/services/apars/AuthenticateApar.java
mock-zosmf/src/main/java/org/zowe/apiml/client/services/apars/FunctionalApar.java
mock-zosmf/src/main/java/org/zowe/apiml/client/services/apars/PH12143.java
mock-zosmf/src/main/java/org/zowe/apiml/client/services/apars/PH34201.java
mock-zosmf/src/main/java/org/zowe/apiml/client/services/apars/PHBase.java
mock-zosmf/src/main/java/org/zowe/apiml/client/services/apars/RSU2012.java
mock-zosmf/src/main/java/org/zowe/apiml/client/services/versions/AvailableApars.java
mock-zosmf/src/main/resources/application.yml
mock-zosmf/src/test/java/org/zowe/apiml/client/services/apars/AuthenticationAparTest.java
mock-zosmf/src/test/java/org/zowe/apiml/client/services/apars/PH12143Test.java
mock-zosmf/src/test/java/org/zowe/apiml/client/services/apars/PH34201Test.java
mock-zosmf/src/test/java/org/zowe/apiml/client/services/apars/PHBaseTest.java

Support for apar PH34201 where no authentication in a request to zOSMF will return a 401 instead of a 500.
Linked to #1326 

fix: support for APAR PH34201

---

caching-service/src/main/resources/application.yml
caching-service/src/test/resources/application.yml
discoverable-client/src/main/resources/application.yml
discoverable-client/src/test/resources/application.yml
metrics-service/src/main/resources/application.yml
onboarding-enabler-spring-sample-app/src/main/resources/application.yml

starting the gateway-url with slash / to make it look consistent with other URLs
Signed-off-by: Adarshdeep Cheema <adarshdeep.cheema@ibm.com>
Linked to # (issue) https://github.com/zowe/api-layer/issues/1173

starting the gateway-url with slash / to make it look consistent with other URLs

---

api-catalog-package/src/main/resources/manifest.yaml
api-catalog-package/src/main/resources/pluginDefinition.json

Fixes https://github.com/zowe/zowe-install-packaging/issues/2336
Change API Catalog to use new way to register itself to AppServer.

fix: define appfwPlugins instead of desktopIframePlugins for API Catalog

---

discovery-package/src/main/resources/zosmf-static-definition.yaml.template

Adds configuration to the z/OSMF static definition to direct the Gateway to strip the `Origin` header. This allows the explorer UIs to use z/OSMF APIs.

feat: Ignore Origin header for z/OSMF

---

gateway-service/src/main/java/org/zowe/apiml/gateway/filters/post/PerServiceAddResponseHeadersFilter.java
gateway-service/src/test/java/org/zowe/apiml/acceptance/AddHeadersPerServiceTest.java
gateway-service/src/test/java/org/zowe/apiml/acceptance/netflix/MetadataBuilder.java
gateway-service/src/test/java/org/zowe/apiml/gateway/filters/post/PerServiceAddResponseHeadersFilterTest.java

Adds `customMetadata.apiml.response.headers` for service configuration that the APIML will use to add or override headers in the response.
Linked to #1743 

feat: Per service configuration to direct the APIML to add headers

---

gateway-package/src/main/resources/bin/start.sh
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/saf/SafProviderBeansConfig.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/saf/SafRestAuthenticationService.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/saf/SafRestAuthenticationServiceTest.java

This PR is part of https://github.com/zowe/zowe-install-packaging/pull/2416 to support the process of definying and scanning extensions for API ML.
* Since SAF authenticate endpoint also requires the password in the payload, the SAF IDT provider we have implemented will generate the password using Passticket and use it 
* Add props to the gateway `start.sh` to append extenders folder to the class path (the code is in https://github.com/zowe/zowe-install-packaging/pull/2416), the solution is described here https://github.com/zowe/zowe-install-packaging/issues/2405
Linked to #1630 

chore: Update SAF IDT provider and add GW sharedlibs props

---

api-catalog-services/src/main/resources/application.yml
caching-service/src/main/resources/application.yml
discovery-service/src/main/resources/application.yml

Disable hystrix command timeout.

fix: Disable hystrix timeout

---

config/local/mock-zosmf.yml
mock-zosmf/src/main/java/org/zowe/apiml/client/services/apars/AuthenticateApar.java
mock-zosmf/src/main/java/org/zowe/apiml/client/services/apars/FunctionalApar.java
mock-zosmf/src/main/java/org/zowe/apiml/client/services/apars/PH12143.java
mock-zosmf/src/main/java/org/zowe/apiml/client/services/apars/PH34201.java
mock-zosmf/src/main/java/org/zowe/apiml/client/services/apars/RSU2012.java
mock-zosmf/src/main/java/org/zowe/apiml/client/services/versions/AvailableApars.java
mock-zosmf/src/main/java/org/zowe/apiml/client/services/versions/Versions.java
mock-zosmf/src/main/resources/application.yml
mock-zosmf/src/test/java/org/zowe/apiml/client/services/apars/AuthenticationAparTest.java
mock-zosmf/src/test/java/org/zowe/apiml/client/services/apars/PH12143Test.java
mock-zosmf/src/test/java/org/zowe/apiml/client/services/apars/PH34201Test.java
mock-zosmf/src/test/java/org/zowe/apiml/client/services/apars/RSU2012Test.java
mock-zosmf/src/test/java/org/zowe/apiml/client/services/versions/AvailableAparsTest.java
mock-zosmf/src/test/java/org/zowe/apiml/client/services/versions/VersionsTest.java
package.json

There was a change in the creation and verification of the token in the mock zOSMF, this makes the property configurable with 10-minute default for a local run. 
Linked to #1883

chore: Configure the timeout for JWT token in mock zOSMF

---

metrics-service-ui/frontend/public/hystrix-dashboard/monitor/monitor.js

Add a check such that only the hystrix streams that match the selected one to display are added in the hystrix dashboard UI.

fix: Remove duplicated hystrix streams in Metrics Service dashboard

---

metrics-service-ui/frontend/public/hystrix-dashboard/monitor/monitor.js

When stream is changed in Metrics Service release connection to previous stream. This stops leaky connections that fill connection pools and memory.

Fix: Release Metrics Service connection when change stream

---

api-catalog-ui/frontend/src/components/Swagger/Swagger.jsx
api-catalog-ui/frontend/src/components/Swagger/Swagger.test.jsx

Fixes the transformation for swagger server URLs to be the location of the current browser location.
Linked to #1882 

Fix: Swagger server url transform

---

api-catalog-services/build.gradle
caching-service/build.gradle
discoverable-client/build.gradle
discovery-service/build.gradle
gateway-service/build.gradle
metrics-service/build.gradle
mock-zosmf/build.gradle

The new version of jgit(v6) is not compatible with Java 8. It is a transitive dependency in gradle-git-properties plugin. This PR will lock jgit on version 5.

fix: specify jgit dependency for gradle plugin

---

common-service-core/src/main/java/org/zowe/apiml/security/HttpsFactory.java
common-service-core/src/test/java/org/zowe/apiml/security/SecurityTestUtils.java

HTTP client is choosing the first key certificate pair returned from the keyring. In some cases, this could lead to the use of the wrong key certificate pair.

fix: choose correct key by alias

---

common-service-core/src/main/java/org/zowe/apiml/product/routing/RoutedServices.java
common-service-core/src/test/java/org/zowe/apiml/product/routing/RoutedServicesTest.java

API catalog transforming homepage URL doesn't count with the possibility of missing context path or prefix.

accept homepage without context path

---

api-catalog-ui/frontend/src/components/Error/Error.jsx
api-catalog-ui/frontend/src/components/Error/Error.test.jsx
api-catalog-ui/frontend/src/components/Error/ErrorDialog.jsx
api-catalog-ui/frontend/src/components/Error/ErrorDialog.test.jsx
api-catalog-ui/frontend/src/components/Error/ErrorFormatter.jsx
api-catalog-ui/frontend/src/components/ErrorBoundary/BigShield/BigShield.jsx
api-catalog-ui/frontend/src/components/ErrorBoundary/Shield/Shield.jsx
api-catalog-ui/frontend/src/components/ServiceTab/InstanceInfo.jsx

Migrate:
1. Error and ErrorDialog
2. Shield and BigShield
3. InstanceInfo
Linked to #1892 

feat: Migrate Error components to Material 

---

common-service-core/src/main/resources/core-log-messages.yml

Make ZWEAM511E message more accurate by making the reported error more generic, as there could be many different causes of this error. Adds further possible actions to the message, included generic suggesting of reviewing the debug log for more info on the error.
Linked to #1871 

Fix: Make ZWEAM511E message more accurate

---

apiml-common/src/main/resources/logback.xml
apiml-utility/src/main/java/org/zowe/apiml/product/logging/MaskingLogPatternLayout.java
apiml-utility/src/test/java/org/zowe/apiml/product/logging/MaskingLogPatternLayoutTest.java
caching-service/src/main/resources/logback.xml
metrics-service/src/main/resources/logback.xml

Adds a log masker that can be configured to mask sensitive information in logs. Currently masks `password` and `newPassword` in request bodies.

Fix: Add log masking class for sensitive logs

---

.github/workflows/release.yml
.github/workflows/specific-release.yml
build.gradle

When the specific and automated release workflows are ran, they commit to master 3 times, triggering 3 snapshot releases. These 3 commits are 1) updating `onboarding-enabler-nodejs/package.json` version 2) setting `gradle.properties` version to the appropriate version for release, and 3) incrementing `gradle.properties` version to the next snapshot tag. We don't need a snapshot build for each of these commits, so with this PR only the 3rd commit (incrementing to snapshot tag) will trigger a snapshot build.
Linked to #1952

chore: Reduce ci duplication when releasing

---

.github/workflows/build-conformant-images.yml

Increase timeout for building images.

chore: Increase image build timeout

---

api-catalog-ui/frontend/src/components/ServiceTab/ServiceTab.jsx

Change homepage label in case of service down to `Service Homepage` to be consistent.
Fixes #2011 

fix: Change homepage label to be consistent

---

api-catalog-package/src/main/resources/plugin/pluginDefinition.json

I hope I'm targeting the right v2 branch. 
Currently, the api catalog app in the desktop does not work in the v2 previews I've seen, due to the iframe pointer URL ending with apicatalog rather than beginning with it. I've marked the plugin version as 2.0.0 to correspond to this change.
Not a realistic breaking change, but if someone were to install this on a very old (like, 1.2?) version of zowe then the url may not work there, so just marking v2 to be safe.
I'm working off of a build https://github.com/zowe/zowe-install-packaging/pull/2568 to confirm if I can/cant load api-catalog. When I make these edits locally, the catalog works!

Fix: Updated URL for api catalog desktop app

---

.github/actions/image-publish-setup/action.yml
.github/workflows/build-conformant-images.yml
.github/workflows/create-image-without-release.yml
.github/workflows/release.yml
.github/workflows/snapshot-release.yml
.github/workflows/specific-release.yml

Publish images to appropriate location of `docker-snapshot` or `docker-release` based on workflow and version tag.
Linked to #2048

fix: publish images to appropriate Artifactory location

---

common-service-core/src/test/java/org/zowe/apiml/config/ApiInfoTest.java
gateway-service/src/test/java/org/zowe/apiml/acceptance/CompressPerServiceTest.java

Fix Sonar issue "JUnit5 test classes and methods should have default package visibility"
Signed-off-by: Yelyzaveta Chebanova <yelyzaveta.chebanova@broadcom.com>
Fix Sonar issue "JUnit5 test classes and methods should have default package visibility"
Linked to #1853 

chore: fix Sonar issue in tests

---

.github/workflows/binary-snapshot-release.yml
.github/workflows/build-conformant-images.yml
.github/workflows/image-snapshot-release.yml

Separate image and binary snapshot release so snapshot release workflow is more clear when there are failures due to our code. Also increase image jobs timeouts to reduce number of failures.
Linked to #2074 

chore: separate snapshot release of images and binaries

---

api-catalog-ui/frontend/package.json
metrics-service-ui/frontend/package.json

When attempting build on some Windows systems, the npm lint script in the metrics-service and api-catalog ui gives a error saying that the file matching the pattern are not found. Replacing the single quote with an escaped double quote fixes this issue and allows the build to proceed.

fix: cross platform support for npm lint

---

.github/workflows/ci-tests.yml

Sonar scan builds fail due to timeout, this increases the timeout.

chore: increase sonar scan timeout

---

caching-service/.gitignore

Add `.gitignore` to ignore `caching-service/index`, which is created during builds by infinispan

chore: add gitignore for caching-service/index

---

gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/zosmf/ZosmfService.java
mock-services/README.md
mock-services/src/main/java/org/zowe/apiml/client/api/AuthenticationController.java
mock-services/src/main/java/org/zowe/apiml/client/model/LoginBody.java
mock-services/src/main/java/org/zowe/apiml/client/services/AparBasedService.java
mock-services/src/main/java/org/zowe/apiml/client/services/apars/FunctionalApar.java
mock-services/src/main/java/org/zowe/apiml/client/services/apars/PH34912.java
mock-services/src/main/java/org/zowe/apiml/client/services/versions/AvailableApars.java
mock-services/src/test/java/org/zowe/apiml/client/services/apars/PH34912Test.java

Implement the change password support to mock zosmf

chore: Add password change to mock zosmf

---

common-service-core/src/main/java/org/zowe/apiml/security/HttpsFactory.java
common-service-core/src/main/java/org/zowe/apiml/security/SecurityUtils.java
discoverable-client/src/main/java/org/zowe/apiml/client/model/DiscoverableClientConfig.java
onboarding-enabler-java/src/main/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidator.java
onboarding-enabler-java/src/test/java/org/zowe/apiml/eurekaservice/client/util/EurekaInstanceConfigValidatorTest.java
zaas-client/src/main/java/org/zowe/apiml/zaasclient/service/internal/ZaasHttpsClientProvider.java

Users will not be required to pass keyAlias. This PR will also make it possible to use two slashes in keyring configuration. It is still preferable to use 4 slashes.
Linked to #2034 

fix: do not require keyAlias

---

common-service-core/src/main/java/org/zowe/apiml/message/api/ApiMessage.java
common-service-core/src/main/java/org/zowe/apiml/message/core/Message.java
common-service-core/src/test/java/org/zowe/apiml/message/core/MessageTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/SecurityErrorCheckTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/error/check/ServiceErrorCheckTest.java

Add `messageAction` and `messageReason` fields to the REST error responses.
Fixes to #2067 

fix: Add missing fields in error response

---

docs/ide-setup.md

Line in ide-setup.md where it mentions "repeat the above.." is missing the 5 modules that include the application main classes and their service names. The below are now included:
- gateway-service
- discovery-service
- mock-services
- api-catalog-services
- discoverable-client
Linked to # ([2122](https://github.com/zowe/api-layer/pull/2122))

docs: update IntelliJ setup to include all services that need to be run

---

api-catalog-ui/frontend/src/components/Header/Header.jsx
api-catalog-ui/frontend/src/components/Header/Header.test.jsx

Fixes link for API Catalog icon in the header.
Linked to #2089 

fix: API Catalog icon links to dashboard

---

gateway-service/src/main/resources/gateway-api-doc.json
gateway-service/src/test/resources/api-doc.json

Document x509 authentication in the Gateway API Documentation.
Fixes #1171 

fix: Document x509 auth in GW API doc

---

gateway-service/src/main/resources/application.yml
integration-tests/src/test/java/org/zowe/apiml/functional/gateway/GatewayTimeoutTest.java

fix: configure southbound timeout with APIML_GATEWAY_TIMEOUT_MILLIS

---

.github/actions/setup/action.yml
.github/workflows/containers.yml

Within the HA runs permissions on .gradle are changed to 700. For the cache to work properly the permissions need to be 755.
Linked to #2160

chore: Update permissions after HA run

---

api-catalog-package/src/main/resources/bin/start.sh
caching-service-package/src/main/resources/bin/start.sh
discovery-package/src/main/resources/bin/start.sh
gateway-package/src/main/resources/bin/start.sh
metrics-service-package/src/main/resources/bin/start.sh

Use `tr` instead of `upper_case` in start script so zowe-launch-scripts isn't required.

fix: Use tr instead of upper_case

---

zaas-client/src/main/java/org/zowe/apiml/zaasclient/config/ConfigProperties.java
zaas-client/src/main/java/org/zowe/apiml/zaasclient/config/DefaultZaasClientConfiguration.java
zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientApimlBaseUrlTest.java

Signed-off-by: Amanda D'Errico <amanda.derrico@ibm.com>
Users can now have both paths `api/v1/gateway/auth` and `gateway/api/v1/auth` be compatible with Zowe v2.x.x. If the old `api/v1/gateway/auth` is provided for apiml.gatewayAuthEndpoint, update that to `gateway/api/v1/auth` before initializing the ZaasClientImpl constructor.
Linked to # ([2182](https://github.com/zowe/api-layer/issues/2182))

fix: zaas client supports v2 compatibility with both gateway endpoint base Url paths

---

integration-tests/src/test/java/org/zowe/apiml/util/config/ConfigReaderZaasClient.java
zaas-client/src/test/java/org/zowe/apiml/zaasclient/service/internal/ZaasClientImplHttpTests.java

Signed-off-by: Amanda D'Errico <amanda.derrico@ibm.com>
Added v2 base path support in integration tests and ZaasClientImplHttpTests
Linked to # ([2182](https://github.com/zowe/api-layer/issues/2182))

chore: Improved integration and unit tests for v1 and v2 base urls

---

common-service-core/src/main/java/org/zowe/apiml/auth/Authentication.java
gateway-service/src/main/java/org/zowe/apiml/gateway/filters/pre/ServiceAuthenticationFilter.java
gateway-service/src/main/java/org/zowe/apiml/gateway/ribbon/http/ServiceAuthenticationDecorator.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImpl.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/AbstractAuthenticationScheme.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketScheme.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/SafIdtScheme.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ServiceAuthenticationService.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZosmfScheme.java
gateway-service/src/test/java/org/zowe/apiml/gateway/filters/pre/ServiceAuthenticationFilterTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/ribbon/http/ServiceAuthenticationDecoratorTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImplTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketSchemeTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/SafIdtSchemeTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ZosmfSchemeTest.java

This PR moves the logic for getting the authentication source from request into schemes.
The motivation for the change: only when specific scheme is chosen (directly or after load balancer) then we can correctly select the source of authentication in case there is more than one present in request.
Linked to #2198 

feat: Enhance x509 authentication scheme to support client certificates (part 1)

---

gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImpl.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/AuthenticationSchemeFactory.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ByPassScheme.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/HttpBasicPassTicketScheme.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/IAuthenticationScheme.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/SafIdtScheme.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/X509Scheme.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZosmfScheme.java
gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZoweJwtScheme.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/ServiceAuthenticationServiceImplTest.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/AuthenticationSchemeFactoryTest.java

Signed-off-by: Yelyzaveta Chebanova <yelyzaveta.chebanova@broadcom.com>
Rename interface AbstractAuthenticationScheme into IAuthenticationScheme.
Linked to #2198 

chore: rename AbstractAuthenticationScheme interface

---

api-catalog-ui/frontend/src/components/Header/Header.jsx

Fixes the heading API Catalog text link to be rendered as an `h3`
Linked to #1555 
- [n/a] I have commented my code, particularly in hard-to-understand areas. In JS I did provide JSDoc
- [n/a] The java tests in the area I was working on leverage @Nested annotations

fix: API Catalog heading changed #1555

---

.github/workflows/containers.yml
discovery-service/src/main/java/org/zowe/apiml/discovery/ApimlInstanceRegistry.java
discovery-service/src/test/java/org/zowe/apiml/discovery/ApimlInstanceRegistryTest.java

Add regex support for the service id prefix replacer. It supports:
1. ca*,bcm
2. ca*,bcm*
3. ca,bcm
4. ca,bcm*
Even uppercase.
Linked to #1999 

fix: Add support for regex

---

gateway-service/src/main/java/org/zowe/apiml/gateway/security/service/schema/ZosmfScheme.java
gateway-service/src/test/java/org/zowe/apiml/gateway/security/service/schema/ZosmfSchemeTest.java

Signed-off-by: Yelyzaveta Chebanova <yelyzaveta.chebanova@broadcom.com>
use default expiration time in Zosmf scheme for auth. source without expiration
Linked to #2246 

feat: use default expiration time in Zosmf scheme

---

discovery-service/src/main/java/org/zowe/apiml/discovery/health/DiscoveryServiceHealthIndicator.java
discovery-service/src/main/resources/application.yml
discovery-service/src/test/java/org/zowe/apiml/discovery/health/DiscoveryServiceHealthIndicatorTest.java
discovery-service/src/test/resources/application.yml

This change enables the discovery service health endpoint to return details even when not authenticated. Those details contain the status of the gateway service. The status of the gateway service does not influence the discovery service status, i.e. it remains UP even when the gateway is DOWN.
Sample status:
```
{"status":"UP","components":{"discoveryService":{"status":"UP","details":{"gateway":"DOWN"}}}}
```
Linked to #1549 

feat: Discovery service health check

---

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocController.java
api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/controllers/handlers/CatalogApiDocControllerExceptionHandler.java
api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/APIServiceStatusService.java
api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocControllerApiDocNotFoundTest.java
api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/controllers/api/CatalogApiDocControllerTest.java
api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/status/ApiServiceStatusServiceTest.java
integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogAuthenticationTest.java
integration-tests/src/test/java/org/zowe/apiml/functional/apicatalog/ApiCatalogEndpointIntegrationTest.java

- Create endpoint `/apidoc/{serviceId}` that will return the default swagger doc for the given service. The default swagger doc functionality was already made, this endpoint just exposes it directly. The default doc is the `apiInfo` marked with `defaultApi: true`, and if none are marked as default then the highest major version is used. If there is no swagger doc then 404 is returned.
- Change behaviour for the specific version apidoc endpoint `/apidoc/{serviceId}/{apiId}` to return 404 if there is no matching swagger, instead of returning the "first" swagger.
Linked to #2320

feat: Create endpoint to retrieve default API doc for service

---

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/cached/CachedApiDocService.java
api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/APIDocRetrievalService.java
api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/services/status/APIServiceStatusService.java
api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/SubstituteSwaggerGenerator.java
api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3Service.java
api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/cached/CachedApiDocServiceTest.java
api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/status/ApiServiceStatusServiceTest.java
api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/services/status/LocalApiDocServiceTest.java

Add better logging for server side code in  API Catalog that handles swagger, errors and warnings are logged and more debug information is logged. This will greatly help with debugging why a swagger document isn't rendered in the Catalog.
Linked to #2315

fix: Add server side logging for swagger handling code

---

common-service-core/src/main/java/org/zowe/apiml/security/HttpsFactory.java

Value of `verifySslCertificatesOfServices` takes full precedence over `nonStrictVerifySslCertificatesOfServices` for hostname verification.

fix: verify ssl certs takes precedence over nonstrict verify

---

caching-service/src/main/java/org/zowe/apiml/caching/service/vsam/config/VsamConfig.java

Fixes the default values of `caching.storage.vsam.keyLength` and `caching.storage.vsam.recordLength` to match those in the JCL of zowe-install-packaging.
Linked to #2203

fix: use same key and record lengths as jcl

---

api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV2Service.java
api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3Service.java
api-catalog-services/src/main/java/org/zowe/apiml/apicatalog/swagger/api/OpenApiUtil.java
api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV2ServiceTest.java
api-catalog-services/src/test/java/org/zowe/apiml/apicatalog/swagger/api/ApiDocV3ServiceTest.java
gateway-service/src/main/resources/application.yml

- Fixes swagger link in API Catalog using incorrect API version
- Add API version to Gateway
Linked to #2336, #2342

fix: API Catalog swagger link

---

api-catalog-package/src/main/resources/bin/start.sh
caching-service-package/src/main/resources/bin/start.sh
discovery-package/src/main/resources/bin/start.sh
gateway-package/src/main/resources/bin/start.sh
metrics-service-package/src/main/resources/bin/start.sh

This should completely fix potential errors in lifecycle scripts. Reported in slack zowe-user channel:
in the server startup log, I see this line:
```
[: FSUM6807 expression syntax error
```
The exact line causes this error is gateway start.sh:
```
if [ ${ZWE_configs_apiml_catalog_serviceId} = "none" ]
then
APIML_GATEWAY_CATALOG_ID=""
fi
```
This issue should also exist in v1 since there is similar code https://github.com/zowe/api-layer/blob/master/gateway-package/src/main/resources/bin/start.sh#L67.

improve shell if checks
